import { Subject, Unit, Topic, Quiz, Prompt, LeaderboardEntry } from '../types';

export const subjects: Subject[] = [
  {
    id: 'maths',
    name: 'Mathematics',
    examBoard: 'Edexcel Higher',
    description: 'GCSE Mathematics covering Number, Algebra, Geometry',
    icon: '📐',
    themeColor: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'biology',
    name: 'Biology',
    examBoard: 'AQA',
    description: 'GCSE Biology covering Cell Biology, Organisation, Disease',
    icon: '🧬',
    themeColor: 'from-green-500 to-emerald-500',
  },
  {
    id: 'history',
    name: 'History',
    examBoard: 'Edexcel',
    description: 'GCSE History covering Modern World History',
    icon: '📜',
    themeColor: 'from-amber-500 to-orange-500',
  },
];

export const units: Unit[] = [
  { id: 'maths-u1', subjectId: 'maths', name: 'Number', orderIndex: 1, description: 'Operations with fractions, decimals, percentages' },
  { id: 'maths-u2', subjectId: 'maths', name: 'Algebra', orderIndex: 2, description: 'Equations, expressions, factorising' },
  { id: 'maths-u3', subjectId: 'maths', name: 'Geometry', orderIndex: 3, description: 'Pythagoras, trigonometry, circle theorems' },

  { id: 'bio-u1', subjectId: 'biology', name: 'Cell Biology', orderIndex: 1, description: 'Cell structure and division' },
  { id: 'bio-u2', subjectId: 'biology', name: 'Organisation', orderIndex: 2, description: 'Digestive and circulatory systems' },
  { id: 'bio-u3', subjectId: 'biology', name: 'Infection & Response', orderIndex: 3, description: 'Pathogens and immune system' },

  { id: 'hist-u1', subjectId: 'history', name: 'Weimar & Nazi Germany', orderIndex: 1, description: '1918-1939' },
  { id: 'hist-u2', subjectId: 'history', name: 'Medicine Through Time', orderIndex: 2, description: 'Medieval to modern medicine' },
  { id: 'hist-u3', subjectId: 'history', name: 'Cold War', orderIndex: 3, description: '1945-1991' },
];

export const topics: Topic[] = [
  { id: 'maths-t1', subjectId: 'maths', unitId: 'maths-u1', name: 'Fractions & Decimals', orderIndex: 1, description: 'Operations with fractions and decimals' },
  { id: 'maths-t2', subjectId: 'maths', unitId: 'maths-u1', name: 'Percentages', orderIndex: 2, description: 'Calculate percentages and percentage change' },
  { id: 'maths-t3', subjectId: 'maths', unitId: 'maths-u2', name: 'Linear Equations', orderIndex: 3, description: 'Solve linear equations' },
  { id: 'maths-t4', subjectId: 'maths', unitId: 'maths-u2', name: 'Factorising', orderIndex: 4, description: 'Factorise algebraic expressions' },
  { id: 'maths-t5', subjectId: 'maths', unitId: 'maths-u3', name: 'Pythagoras', orderIndex: 5, description: 'Apply Pythagoras theorem' },
  { id: 'maths-t6', subjectId: 'maths', unitId: 'maths-u3', name: 'Circle Theorems', orderIndex: 6, description: 'Apply circle theorems' },

  { id: 'bio-t1', subjectId: 'biology', unitId: 'bio-u1', name: 'Cell Structure', orderIndex: 1, description: 'Structure of plant and animal cells' },
  { id: 'bio-t2', subjectId: 'biology', unitId: 'bio-u1', name: 'Cell Division', orderIndex: 2, description: 'Mitosis and meiosis' },
  { id: 'bio-t3', subjectId: 'biology', unitId: 'bio-u2', name: 'Digestive System', orderIndex: 3, description: 'Organs and enzymes in digestion' },
  { id: 'bio-t4', subjectId: 'biology', unitId: 'bio-u2', name: 'Blood & Circulation', orderIndex: 4, description: 'Heart and blood vessels' },
  { id: 'bio-t5', subjectId: 'biology', unitId: 'bio-u3', name: 'Pathogens', orderIndex: 5, description: 'Bacteria, viruses, fungi, and protists' },
  { id: 'bio-t6', subjectId: 'biology', unitId: 'bio-u3', name: 'Immune System', orderIndex: 6, description: 'White blood cells and immunity' },

  { id: 'hist-t1', subjectId: 'history', unitId: 'hist-u1', name: 'Weimar Republic', orderIndex: 1, description: 'Early challenges 1918-1923' },
  { id: 'hist-t2', subjectId: 'history', unitId: 'hist-u1', name: 'Hitler\'s Rise', orderIndex: 2, description: 'How Hitler became Chancellor' },
  { id: 'hist-t3', subjectId: 'history', unitId: 'hist-u2', name: 'Medieval Medicine', orderIndex: 3, description: 'Medical knowledge in medieval times' },
  { id: 'hist-t4', subjectId: 'history', unitId: 'hist-u2', name: 'Renaissance Medicine', orderIndex: 4, description: 'Medical advances in Renaissance' },
  { id: 'hist-t5', subjectId: 'history', unitId: 'hist-u3', name: 'Cold War Origins', orderIndex: 5, description: 'How the Cold War began' },
  { id: 'hist-t6', subjectId: 'history', unitId: 'hist-u3', name: 'Cuban Missile Crisis', orderIndex: 6, description: 'The 1962 crisis' },
];

export const prompts: Prompt[] = [
  { id: 'p-maths-1', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t1', type: 'short', question: 'What is 1/2 + 1/4?', answers: ['3/4', '0.75', 'three quarters'], explanation: 'Convert to common denominator: 2/4 + 1/4 = 3/4' },
  { id: 'p-maths-2', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t1', type: 'short', question: 'What is 0.25 as a fraction?', answers: ['1/4', 'one quarter'], hint: '25/100 simplified', explanation: '0.25 = 25/100 = 1/4' },
  { id: 'p-maths-3', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t1', type: 'short', question: 'What is 3/5 as a decimal?', answers: ['0.6'], explanation: '3 ÷ 5 = 0.6' },
  { id: 'p-maths-4', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t1', type: 'short', question: 'What is 2/3 + 1/6?', answers: ['5/6'], explanation: '4/6 + 1/6 = 5/6' },
  { id: 'p-maths-5', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t1', type: 'short', question: 'What is 0.8 × 0.5?', answers: ['0.4', '2/5'], explanation: '0.8 × 0.5 = 0.4' },
  { id: 'p-maths-6', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t1', type: 'short', question: 'What is 3/4 - 1/2?', answers: ['1/4', '0.25'], explanation: '3/4 - 2/4 = 1/4' },
  { id: 'p-maths-7', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t1', type: 'short', question: 'What is 0.125 as a fraction?', answers: ['1/8', 'one eighth'], explanation: '0.125 = 125/1000 = 1/8' },
  { id: 'p-maths-8', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t1', type: 'short', question: 'What is 5/8 as a decimal?', answers: ['0.625'], explanation: '5 ÷ 8 = 0.625' },
  { id: 'p-maths-9', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t1', type: 'short', question: 'What is 1.5 × 2/3?', answers: ['1'], explanation: '3/2 × 2/3 = 6/6 = 1' },
  { id: 'p-maths-10', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t1', type: 'short', question: 'What is 2.5 ÷ 0.5?', answers: ['5'], explanation: '2.5 ÷ 0.5 = 25 ÷ 5 = 5' },

  { id: 'p-maths-11', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t2', type: 'short', question: 'What is 50% of 80?', answers: ['40'], explanation: '80 × 0.5 = 40' },
  { id: 'p-maths-12', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t2', type: 'short', question: 'What is 25% of 200?', answers: ['50'], explanation: '200 × 0.25 = 50' },
  { id: 'p-maths-13', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t2', type: 'short', question: 'What is 10% of 150?', answers: ['15'], explanation: '150 × 0.1 = 15' },
  { id: 'p-maths-14', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t2', type: 'short', question: 'What is 75% of 40?', answers: ['30'], explanation: '40 × 0.75 = 30' },
  { id: 'p-maths-15', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t2', type: 'short', question: 'Increase 100 by 20%. What is the result?', answers: ['120'], explanation: '100 + (100 × 0.2) = 120' },
  { id: 'p-maths-16', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t2', type: 'short', question: 'Decrease 50 by 10%. What is the result?', answers: ['45'], explanation: '50 - (50 × 0.1) = 45' },
  { id: 'p-maths-17', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t2', type: 'short', question: 'What percentage is 20 out of 80?', answers: ['25%', '25'], explanation: '(20 ÷ 80) × 100 = 25%' },
  { id: 'p-maths-18', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t2', type: 'short', question: 'What percentage is 15 out of 60?', answers: ['25%', '25'], explanation: '(15 ÷ 60) × 100 = 25%' },
  { id: 'p-maths-19', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t2', type: 'short', question: 'A price increases from £80 to £100. What is the percentage increase?', answers: ['25%', '25'], explanation: '(20 ÷ 80) × 100 = 25%' },
  { id: 'p-maths-20', subjectId: 'maths', unitId: 'maths-u1', topicId: 'maths-t2', type: 'short', question: 'What is 5% of 600?', answers: ['30'], explanation: '600 × 0.05 = 30' },

  { id: 'p-maths-21', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t3', type: 'short', question: 'Solve: x + 5 = 12', answers: ['7', 'x = 7', 'x=7'], explanation: 'x = 12 - 5 = 7' },
  { id: 'p-maths-22', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t3', type: 'short', question: 'Solve: 2x = 10', answers: ['5', 'x = 5', 'x=5'], explanation: 'x = 10 ÷ 2 = 5' },
  { id: 'p-maths-23', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t3', type: 'short', question: 'Solve: x - 3 = 7', answers: ['10', 'x = 10', 'x=10'], explanation: 'x = 7 + 3 = 10' },
  { id: 'p-maths-24', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t3', type: 'short', question: 'Solve: 3x + 2 = 11', answers: ['3', 'x = 3', 'x=3'], explanation: '3x = 9, so x = 3' },
  { id: 'p-maths-25', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t3', type: 'short', question: 'Solve: 5x - 10 = 15', answers: ['5', 'x = 5', 'x=5'], explanation: '5x = 25, so x = 5' },
  { id: 'p-maths-26', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t3', type: 'short', question: 'Solve: 4x = 20', answers: ['5', 'x = 5', 'x=5'], explanation: 'x = 20 ÷ 4 = 5' },
  { id: 'p-maths-27', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t3', type: 'short', question: 'Solve: 2x + 7 = 15', answers: ['4', 'x = 4', 'x=4'], explanation: '2x = 8, so x = 4' },
  { id: 'p-maths-28', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t3', type: 'short', question: 'Solve: x/2 = 6', answers: ['12', 'x = 12', 'x=12'], explanation: 'x = 6 × 2 = 12' },
  { id: 'p-maths-29', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t3', type: 'short', question: 'Solve: 3x - 5 = 10', answers: ['5', 'x = 5', 'x=5'], explanation: '3x = 15, so x = 5' },
  { id: 'p-maths-30', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t3', type: 'short', question: 'Solve: 6x + 3 = 21', answers: ['3', 'x = 3', 'x=3'], explanation: '6x = 18, so x = 3' },

  { id: 'p-maths-31', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t4', type: 'short', question: 'Factorise: 2x + 4', answers: ['2(x + 2)', '2(x+2)'], explanation: 'HCF is 2: 2(x + 2)' },
  { id: 'p-maths-32', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t4', type: 'short', question: 'Factorise: 3x + 6', answers: ['3(x + 2)', '3(x+2)'], explanation: 'HCF is 3: 3(x + 2)' },
  { id: 'p-maths-33', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t4', type: 'short', question: 'Factorise: 5x + 10', answers: ['5(x + 2)', '5(x+2)'], explanation: 'HCF is 5: 5(x + 2)' },
  { id: 'p-maths-34', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t4', type: 'short', question: 'Factorise: 4x - 8', answers: ['4(x - 2)', '4(x-2)'], explanation: 'HCF is 4: 4(x - 2)' },
  { id: 'p-maths-35', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t4', type: 'short', question: 'Factorise: 6x + 9', answers: ['3(2x + 3)', '3(2x+3)'], explanation: 'HCF is 3: 3(2x + 3)' },
  { id: 'p-maths-36', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t4', type: 'short', question: 'Factorise: x² + 5x', answers: ['x(x + 5)', 'x(x+5)'], explanation: 'HCF is x: x(x + 5)' },
  { id: 'p-maths-37', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t4', type: 'short', question: 'Factorise: 2x² + 4x', answers: ['2x(x + 2)', '2x(x+2)'], explanation: 'HCF is 2x: 2x(x + 2)' },
  { id: 'p-maths-38', subjectId: 'maths', unitId: 'maths-u2', topicId: 'maths-t4', type: 'short', question: 'Factorise: 3x² - 6x', answers: ['3x(x - 2)', '3x(x-2)'], explanation: 'HCF is 3x: 3x(x - 2)' },

  { id: 'p-maths-39', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t5', type: 'short', question: 'Right triangle with sides 3 and 4. Find hypotenuse.', answers: ['5'], explanation: '√(3² + 4²) = √25 = 5' },
  { id: 'p-maths-40', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t5', type: 'short', question: 'Right triangle with sides 5 and 12. Find hypotenuse.', answers: ['13'], explanation: '√(5² + 12²) = √169 = 13' },
  { id: 'p-maths-41', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t5', type: 'short', question: 'Right triangle with sides 6 and 8. Find hypotenuse.', answers: ['10'], explanation: '√(6² + 8²) = √100 = 10' },
  { id: 'p-maths-42', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t5', type: 'short', question: 'Right triangle with hypotenuse 10 and side 6. Find other side.', answers: ['8'], explanation: '√(10² - 6²) = √64 = 8' },
  { id: 'p-maths-43', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t5', type: 'short', question: 'Right triangle with hypotenuse 13 and side 5. Find other side.', answers: ['12'], explanation: '√(13² - 5²) = √144 = 12' },
  { id: 'p-maths-44', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t5', type: 'short', question: 'Right triangle with sides 8 and 15. Find hypotenuse.', answers: ['17'], explanation: '√(8² + 15²) = √289 = 17' },
  { id: 'p-maths-45', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t5', type: 'short', question: 'Right triangle with sides 7 and 24. Find hypotenuse.', answers: ['25'], explanation: '√(7² + 24²) = √625 = 25' },
  { id: 'p-maths-46', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t5', type: 'short', question: 'Right triangle with hypotenuse 5 and side 3. Find other side.', answers: ['4'], explanation: '√(5² - 3²) = √16 = 4' },

  { id: 'p-maths-47', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t6', type: 'short', question: 'Angle in a semicircle is always...', answers: ['90', '90 degrees', 'right angle'], explanation: 'Angles in semicircle = 90°' },
  { id: 'p-maths-48', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t6', type: 'short', question: 'Angles in the same segment are...', answers: ['equal'], explanation: 'Angles subtended in same segment are equal' },
  { id: 'p-maths-49', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t6', type: 'short', question: 'Angle at centre is ____ times angle at circumference', answers: ['2', 'twice', 'double'], explanation: 'Centre angle = 2 × circumference angle' },
  { id: 'p-maths-50', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t6', type: 'short', question: 'Opposite angles in cyclic quadrilateral sum to...', answers: ['180', '180 degrees'], explanation: 'Opposite angles = 180°' },
  { id: 'p-maths-51', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t6', type: 'short', question: 'Tangent meets radius at what angle?', answers: ['90', '90 degrees', 'right angle'], explanation: 'Tangent ⊥ radius' },
  { id: 'p-maths-52', subjectId: 'maths', unitId: 'maths-u3', topicId: 'maths-t6', type: 'short', question: 'Two tangents from external point are...', answers: ['equal', 'equal length'], explanation: 'Tangent lengths from point are equal' },

  { id: 'p-bio-1', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t1', type: 'short', question: 'What controls what enters and leaves a cell?', answers: ['cell membrane', 'membrane'], explanation: 'Cell membrane controls entry/exit' },
  { id: 'p-bio-2', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t1', type: 'short', question: 'What is the jelly-like substance inside cells?', answers: ['cytoplasm'], explanation: 'Cytoplasm is the jelly-like substance' },
  { id: 'p-bio-3', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t1', type: 'short', question: 'What controls all cell activities?', answers: ['nucleus'], explanation: 'Nucleus controls cell activities' },
  { id: 'p-bio-4', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t1', type: 'short', question: 'Where does aerobic respiration occur?', answers: ['mitochondria', 'mitochondrion'], explanation: 'Mitochondria = site of respiration' },
  { id: 'p-bio-5', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t1', type: 'short', question: 'Where does protein synthesis occur?', answers: ['ribosomes', 'ribosome'], explanation: 'Ribosomes make proteins' },
  { id: 'p-bio-6', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t1', type: 'short', question: 'What gives plant cells their rigid structure?', answers: ['cell wall'], explanation: 'Cell wall provides rigidity' },
  { id: 'p-bio-7', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t1', type: 'short', question: 'Where does photosynthesis occur?', answers: ['chloroplasts', 'chloroplast'], explanation: 'Chloroplasts = photosynthesis site' },
  { id: 'p-bio-8', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t1', type: 'short', question: 'What stores cell sap in plant cells?', answers: ['vacuole'], explanation: 'Vacuole stores cell sap' },
  { id: 'p-bio-9', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t1', type: 'short', question: 'What type of cells have a nucleus?', answers: ['eukaryotic', 'eukaryotes'], explanation: 'Eukaryotic cells have nucleus' },
  { id: 'p-bio-10', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t1', type: 'short', question: 'What type of cells lack a nucleus?', answers: ['prokaryotic', 'prokaryotes'], explanation: 'Prokaryotic cells lack nucleus' },

  { id: 'p-bio-11', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t2', type: 'short', question: 'What type of cell division produces identical cells?', answers: ['mitosis'], explanation: 'Mitosis = identical cells' },
  { id: 'p-bio-12', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t2', type: 'short', question: 'What type of cell division produces gametes?', answers: ['meiosis'], explanation: 'Meiosis = gametes' },
  { id: 'p-bio-13', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t2', type: 'short', question: 'How many cells does mitosis produce?', answers: ['2', 'two'], explanation: 'Mitosis → 2 cells' },
  { id: 'p-bio-14', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t2', type: 'short', question: 'How many cells does meiosis produce?', answers: ['4', 'four'], explanation: 'Meiosis → 4 cells' },
  { id: 'p-bio-15', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t2', type: 'short', question: 'What are sex cells called?', answers: ['gametes'], explanation: 'Gametes = sex cells' },
  { id: 'p-bio-16', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t2', type: 'short', question: 'How many chromosomes in human body cells?', answers: ['46'], explanation: '46 chromosomes (23 pairs)' },
  { id: 'p-bio-17', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t2', type: 'short', question: 'How many chromosomes in human gametes?', answers: ['23'], explanation: '23 chromosomes (haploid)' },
  { id: 'p-bio-18', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t2', type: 'short', question: 'What is cell division for growth called?', answers: ['mitosis'], explanation: 'Mitosis for growth' },
  { id: 'p-bio-19', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t2', type: 'short', question: 'What does diploid mean?', answers: ['two sets of chromosomes', 'full set'], explanation: 'Diploid = 2 chromosome sets' },
  { id: 'p-bio-20', subjectId: 'biology', unitId: 'bio-u1', topicId: 'bio-t2', type: 'short', question: 'What does haploid mean?', answers: ['one set of chromosomes', 'half set'], explanation: 'Haploid = 1 chromosome set' },

  { id: 'p-bio-21', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t3', type: 'short', question: 'What enzyme breaks down starch?', answers: ['amylase'], explanation: 'Amylase → starch digestion' },
  { id: 'p-bio-22', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t3', type: 'short', question: 'What enzyme breaks down proteins?', answers: ['protease', 'pepsin'], explanation: 'Protease → protein digestion' },
  { id: 'p-bio-23', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t3', type: 'short', question: 'What enzyme breaks down lipids?', answers: ['lipase'], explanation: 'Lipase → lipid digestion' },
  { id: 'p-bio-24', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t3', type: 'short', question: 'Where is bile produced?', answers: ['liver'], explanation: 'Liver produces bile' },
  { id: 'p-bio-25', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t3', type: 'short', question: 'Where is bile stored?', answers: ['gall bladder', 'gallbladder'], explanation: 'Gall bladder stores bile' },
  { id: 'p-bio-26', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t3', type: 'short', question: 'What does bile do to fats?', answers: ['emulsify', 'emulsifies'], explanation: 'Bile emulsifies fats' },
  { id: 'p-bio-27', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t3', type: 'short', question: 'Where does most absorption occur?', answers: ['small intestine'], explanation: 'Small intestine absorbs nutrients' },
  { id: 'p-bio-28', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t3', type: 'short', question: 'What are the products of starch digestion?', answers: ['glucose', 'sugars'], explanation: 'Starch → glucose' },
  { id: 'p-bio-29', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t3', type: 'short', question: 'What are the products of protein digestion?', answers: ['amino acids'], explanation: 'Proteins → amino acids' },
  { id: 'p-bio-30', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t3', type: 'short', question: 'What are the products of lipid digestion?', answers: ['fatty acids and glycerol', 'glycerol and fatty acids'], explanation: 'Lipids → fatty acids + glycerol' },

  { id: 'p-bio-31', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t4', type: 'short', question: 'What carries oxygen in blood?', answers: ['red blood cells', 'erythrocytes'], explanation: 'RBCs carry oxygen' },
  { id: 'p-bio-32', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t4', type: 'short', question: 'What fights infections in blood?', answers: ['white blood cells', 'leukocytes'], explanation: 'WBCs fight infection' },
  { id: 'p-bio-33', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t4', type: 'short', question: 'What helps blood clot?', answers: ['platelets'], explanation: 'Platelets → clotting' },
  { id: 'p-bio-34', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t4', type: 'short', question: 'What is the liquid part of blood?', answers: ['plasma'], explanation: 'Plasma is liquid component' },
  { id: 'p-bio-35', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t4', type: 'short', question: 'What protein carries oxygen in RBCs?', answers: ['haemoglobin', 'hemoglobin'], explanation: 'Haemoglobin carries O₂' },
  { id: 'p-bio-36', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t4', type: 'short', question: 'Which blood vessel carries blood away from heart?', answers: ['artery', 'arteries'], explanation: 'Arteries → away from heart' },
  { id: 'p-bio-37', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t4', type: 'short', question: 'Which blood vessel carries blood to heart?', answers: ['vein', 'veins'], explanation: 'Veins → to heart' },
  { id: 'p-bio-38', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t4', type: 'short', question: 'What are the smallest blood vessels?', answers: ['capillaries', 'capillary'], explanation: 'Capillaries are smallest' },
  { id: 'p-bio-39', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t4', type: 'short', question: 'Which side of heart pumps to lungs?', answers: ['right'], explanation: 'Right side → lungs' },
  { id: 'p-bio-40', subjectId: 'biology', unitId: 'bio-u2', topicId: 'bio-t4', type: 'short', question: 'Which side of heart pumps to body?', answers: ['left'], explanation: 'Left side → body' },

  { id: 'p-bio-41', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t5', type: 'short', question: 'What are microorganisms that cause disease called?', answers: ['pathogens'], explanation: 'Pathogens cause disease' },
  { id: 'p-bio-42', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t5', type: 'short', question: 'Name a bacterial disease', answers: ['tuberculosis', 'salmonella', 'cholera', 'gonorrhoea'], explanation: 'Many bacterial diseases exist' },
  { id: 'p-bio-43', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t5', type: 'short', question: 'Name a viral disease', answers: ['measles', 'hiv', 'aids', 'flu', 'influenza', 'covid'], explanation: 'Many viral diseases exist' },
  { id: 'p-bio-44', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t5', type: 'short', question: 'What type of pathogen causes malaria?', answers: ['protist', 'protozoa'], explanation: 'Malaria = protist disease' },
  { id: 'p-bio-45', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t5', type: 'short', question: 'What type of pathogen causes athletes foot?', answers: ['fungus', 'fungi'], explanation: 'Athletes foot = fungal' },
  { id: 'p-bio-46', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t5', type: 'short', question: 'How can pathogens spread through air?', answers: ['droplets', 'droplet infection'], explanation: 'Airborne droplets spread disease' },
  { id: 'p-bio-47', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t5', type: 'short', question: 'What is direct contact spread?', answers: ['touching', 'contact'], explanation: 'Direct contact = physical touch' },
  { id: 'p-bio-48', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t5', type: 'short', question: 'What spreads malaria?', answers: ['mosquito', 'mosquitoes'], explanation: 'Mosquitoes = malaria vector' },

  { id: 'p-bio-49', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t6', type: 'short', question: 'What engulfs pathogens?', answers: ['phagocytes'], explanation: 'Phagocytes engulf pathogens' },
  { id: 'p-bio-50', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t6', type: 'short', question: 'What produces antibodies?', answers: ['lymphocytes'], explanation: 'Lymphocytes make antibodies' },
  { id: 'p-bio-51', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t6', type: 'short', question: 'What do antibodies do?', answers: ['bind to antigens', 'destroy pathogens'], explanation: 'Antibodies bind antigens' },
  { id: 'p-bio-52', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t6', type: 'short', question: 'What are unique proteins on pathogens called?', answers: ['antigens'], explanation: 'Antigens = pathogen markers' },
  { id: 'p-bio-53', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t6', type: 'short', question: 'What do memory cells do?', answers: ['remember pathogens', 'provide immunity'], explanation: 'Memory cells = long-term immunity' },
  { id: 'p-bio-54', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t6', type: 'short', question: 'What is immunity from vaccination called?', answers: ['active immunity'], explanation: 'Active immunity from vaccines' },
  { id: 'p-bio-55', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t6', type: 'short', question: 'What do vaccines contain?', answers: ['dead or inactive pathogens', 'antigens'], explanation: 'Vaccines have dead pathogens' },
  { id: 'p-bio-56', subjectId: 'biology', unitId: 'bio-u3', topicId: 'bio-t6', type: 'short', question: 'What produces antitoxins?', answers: ['white blood cells', 'lymphocytes'], explanation: 'WBCs produce antitoxins' },

  { id: 'p-hist-1', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t1', type: 'short', question: 'When did WW1 end?', answers: ['1918', 'november 1918'], explanation: 'WW1 ended November 1918' },
  { id: 'p-hist-2', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t1', type: 'short', question: 'What treaty punished Germany?', answers: ['treaty of versailles', 'versailles'], explanation: 'Treaty of Versailles' },
  { id: 'p-hist-3', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t1', type: 'short', question: 'What was Article 231?', answers: ['war guilt clause', 'war guilt'], explanation: 'War guilt clause' },
  { id: 'p-hist-4', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t1', type: 'short', question: 'How much were reparations (in marks)?', answers: ['£6.6 billion', '6.6 billion', '132 billion marks'], explanation: '£6.6bn or 132bn marks' },
  { id: 'p-hist-5', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t1', type: 'short', question: 'What uprising happened in 1919?', answers: ['spartacist uprising', 'spartacist'], explanation: 'Spartacist Uprising 1919' },
  { id: 'p-hist-6', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t1', type: 'short', question: 'Who led the Spartacists?', answers: ['rosa luxemburg', 'luxemburg', 'karl liebknecht', 'liebknecht'], explanation: 'Luxemburg & Liebknecht' },
  { id: 'p-hist-7', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t1', type: 'short', question: 'What was the 1923 crisis?', answers: ['hyperinflation', 'ruhr crisis'], explanation: 'Hyperinflation 1923' },
  { id: 'p-hist-8', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t1', type: 'short', question: 'Who invaded the Ruhr?', answers: ['france', 'french', 'france and belgium'], explanation: 'France (& Belgium)' },
  { id: 'p-hist-9', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t1', type: 'short', question: 'What is hyperinflation?', answers: ['rapid price increase', 'money loses value'], explanation: 'Rapid price rises' },
  { id: 'p-hist-10', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t1', type: 'short', question: 'What new currency was introduced in 1923?', answers: ['rentenmark'], explanation: 'Rentenmark' },

  { id: 'p-hist-11', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t2', type: 'short', question: 'What was Hitler\'s party called?', answers: ['nazi', 'nsdap', 'nazi party'], explanation: 'Nazi Party (NSDAP)' },
  { id: 'p-hist-12', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t2', type: 'short', question: 'When was the Munich Putsch?', answers: ['1923', 'november 1923'], explanation: 'November 1923' },
  { id: 'p-hist-13', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t2', type: 'short', question: 'What book did Hitler write in prison?', answers: ['mein kampf'], explanation: 'Mein Kampf' },
  { id: 'p-hist-14', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t2', type: 'short', question: 'When did the Wall Street Crash happen?', answers: ['1929', 'october 1929'], explanation: 'October 1929' },
  { id: 'p-hist-15', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t2', type: 'short', question: 'When did Hitler become Chancellor?', answers: ['1933', 'january 1933'], explanation: 'January 1933' },
  { id: 'p-hist-16', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t2', type: 'short', question: 'Who was President when Hitler became Chancellor?', answers: ['hindenburg'], explanation: 'President Hindenburg' },
  { id: 'p-hist-17', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t2', type: 'short', question: 'What fire helped Hitler gain power?', answers: ['reichstag fire'], explanation: 'Reichstag Fire 1933' },
  { id: 'p-hist-18', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t2', type: 'short', question: 'What was the 1933 act that gave Hitler full power?', answers: ['enabling act'], explanation: 'Enabling Act 1933' },
  { id: 'p-hist-19', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t2', type: 'short', question: 'What was Night of the Long Knives?', answers: ['purge of sa', 'killing of rohm'], explanation: 'SA purge 1934' },
  { id: 'p-hist-20', subjectId: 'history', unitId: 'hist-u1', topicId: 'hist-t2', type: 'short', question: 'Who led the SA?', answers: ['rohm', 'ernst rohm'], explanation: 'Ernst Röhm' },

  { id: 'p-hist-21', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t3', type: 'short', question: 'What theory said illness was caused by bad air?', answers: ['miasma', 'miasma theory'], explanation: 'Miasma theory' },
  { id: 'p-hist-22', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t3', type: 'short', question: 'What theory blamed imbalanced fluids?', answers: ['four humours', 'theory of four humours'], explanation: 'Four Humours' },
  { id: 'p-hist-23', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t3', type: 'short', question: 'Who created the Four Humours theory?', answers: ['galen'], explanation: 'Galen' },
  { id: 'p-hist-24', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t3', type: 'short', question: 'What was bloodletting?', answers: ['removing blood', 'draining blood'], explanation: 'Removing blood as treatment' },
  { id: 'p-hist-25', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t3', type: 'short', question: 'What did people believe caused disease in medieval times?', answers: ['god', 'punishment', 'sin'], explanation: 'God/punishment/sin' },
  { id: 'p-hist-26', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t3', type: 'short', question: 'What was a common medieval hospital?', answers: ['monastery', 'church'], explanation: 'Monastery/church hospitals' },
  { id: 'p-hist-27', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t3', type: 'short', question: 'What was the Black Death?', answers: ['plague', 'bubonic plague'], explanation: 'Bubonic plague' },
  { id: 'p-hist-28', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t3', type: 'short', question: 'When was the Black Death?', answers: ['1348', '1348-1350', '14th century'], explanation: '1348-1350' },

  { id: 'p-hist-29', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t4', type: 'short', question: 'Who challenged Galen?', answers: ['vesalius', 'andreas vesalius'], explanation: 'Vesalius challenged Galen' },
  { id: 'p-hist-30', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t4', type: 'short', question: 'What book did Vesalius write?', answers: ['fabric of the human body', 'fabrica'], explanation: 'Fabric of Human Body (Fabrica)' },
  { id: 'p-hist-31', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t4', type: 'short', question: 'Who discovered blood circulation?', answers: ['harvey', 'william harvey'], explanation: 'William Harvey' },
  { id: 'p-hist-32', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t4', type: 'short', question: 'What technology helped Renaissance medicine?', answers: ['printing press'], explanation: 'Printing press spread knowledge' },
  { id: 'p-hist-33', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t4', type: 'short', question: 'What did Renaissance doctors use to learn anatomy?', answers: ['dissection', 'dissections'], explanation: 'Dissection' },
  { id: 'p-hist-34', subjectId: 'history', unitId: 'hist-u2', topicId: 'hist-t4', type: 'short', question: 'What did Harvey discover about the heart?', answers: ['it pumps blood', 'pump'], explanation: 'Heart as pump' },

  { id: 'p-hist-35', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t5', type: 'short', question: 'When did WW2 end?', answers: ['1945'], explanation: '1945' },
  { id: 'p-hist-36', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t5', type: 'short', question: 'What were the two superpowers?', answers: ['usa and ussr', 'ussr and usa'], explanation: 'USA & USSR' },
  { id: 'p-hist-37', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t5', type: 'short', question: 'What was the USA\'s economic system?', answers: ['capitalism'], explanation: 'Capitalism' },
  { id: 'p-hist-38', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t5', type: 'short', question: 'What was the USSR\'s economic system?', answers: ['communism'], explanation: 'Communism' },
  { id: 'p-hist-39', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t5', type: 'short', question: 'Who was the US President at the start of the Cold War?', answers: ['truman', 'harry truman'], explanation: 'Harry Truman' },
  { id: 'p-hist-40', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t5', type: 'short', question: 'Who was the Soviet leader after WW2?', answers: ['stalin', 'joseph stalin'], explanation: 'Joseph Stalin' },
  { id: 'p-hist-41', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t5', type: 'short', question: 'What doctrine promised US aid to resist communism?', answers: ['truman doctrine'], explanation: 'Truman Doctrine' },
  { id: 'p-hist-42', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t5', type: 'short', question: 'What plan gave economic aid to Europe?', answers: ['marshall plan'], explanation: 'Marshall Plan' },
  { id: 'p-hist-43', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t5', type: 'short', question: 'What was the military alliance of Western powers?', answers: ['nato'], explanation: 'NATO' },
  { id: 'p-hist-44', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t5', type: 'short', question: 'What was the Soviet response to NATO?', answers: ['warsaw pact'], explanation: 'Warsaw Pact' },

  { id: 'p-hist-45', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t6', type: 'short', question: 'When was the Cuban Missile Crisis?', answers: ['1962', 'october 1962'], explanation: 'October 1962' },
  { id: 'p-hist-46', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t6', type: 'short', question: 'Who was US President during crisis?', answers: ['kennedy', 'jfk', 'john f kennedy'], explanation: 'JFK (Kennedy)' },
  { id: 'p-hist-47', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t6', type: 'short', question: 'Who was Soviet leader during crisis?', answers: ['khrushchev', 'nikita khrushchev'], explanation: 'Khrushchev' },
  { id: 'p-hist-48', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t6', type: 'short', question: 'Who led Cuba?', answers: ['castro', 'fidel castro'], explanation: 'Fidel Castro' },
  { id: 'p-hist-49', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t6', type: 'short', question: 'What did USA do to Cuba?', answers: ['blockade', 'quarantine'], explanation: 'Blockaded Cuba' },
  { id: 'p-hist-50', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t6', type: 'short', question: 'What did USSR remove from Cuba?', answers: ['missiles', 'nuclear missiles'], explanation: 'Nuclear missiles' },
  { id: 'p-hist-51', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t6', type: 'short', question: 'What did USA remove from Turkey?', answers: ['missiles'], explanation: 'Missiles from Turkey' },
  { id: 'p-hist-52', subjectId: 'history', unitId: 'hist-u3', topicId: 'hist-t6', type: 'short', question: 'What hotline was set up after?', answers: ['moscow-washington', 'red phone', 'hotline'], explanation: 'Moscow-Washington hotline' },
];

export const quizzes: Quiz[] = [
  {
    id: 'maths-topic-fractions',
    subjectId: 'maths',
    scopeType: 'topic',
    topicId: 'maths-t1',
    unitId: 'maths-u1',
    title: 'Fractions & Decimals Sprint',
    description: 'Master operations with fractions and decimals',
    timeLimitSec: 180,
    grade9TargetSec: 90,
    promptIds: ['p-maths-1', 'p-maths-2', 'p-maths-3', 'p-maths-4', 'p-maths-5', 'p-maths-6', 'p-maths-7', 'p-maths-8', 'p-maths-9', 'p-maths-10'],
  },
  {
    id: 'maths-topic-percentages',
    subjectId: 'maths',
    scopeType: 'topic',
    topicId: 'maths-t2',
    unitId: 'maths-u1',
    title: 'Percentages Quick Fire',
    description: 'Calculate percentages and percentage change',
    timeLimitSec: 240,
    grade9TargetSec: 120,
    promptIds: ['p-maths-11', 'p-maths-12', 'p-maths-13', 'p-maths-14', 'p-maths-15', 'p-maths-16', 'p-maths-17', 'p-maths-18', 'p-maths-19', 'p-maths-20'],
  },
  {
    id: 'maths-topic-equations',
    subjectId: 'maths',
    scopeType: 'topic',
    topicId: 'maths-t3',
    unitId: 'maths-u2',
    title: 'Linear Equations Drill',
    description: 'Solve linear equations quickly',
    timeLimitSec: 300,
    grade9TargetSec: 150,
    promptIds: ['p-maths-21', 'p-maths-22', 'p-maths-23', 'p-maths-24', 'p-maths-25', 'p-maths-26', 'p-maths-27', 'p-maths-28', 'p-maths-29', 'p-maths-30'],
  },
  {
    id: 'maths-topic-factorising',
    subjectId: 'maths',
    scopeType: 'topic',
    topicId: 'maths-t4',
    unitId: 'maths-u2',
    title: 'Factorising Fundamentals',
    description: 'Factorise algebraic expressions',
    timeLimitSec: 240,
    grade9TargetSec: 120,
    promptIds: ['p-maths-31', 'p-maths-32', 'p-maths-33', 'p-maths-34', 'p-maths-35', 'p-maths-36', 'p-maths-37', 'p-maths-38'],
  },
  {
    id: 'maths-topic-pythagoras',
    subjectId: 'maths',
    scopeType: 'topic',
    topicId: 'maths-t5',
    unitId: 'maths-u3',
    title: 'Pythagoras Rapid Recall',
    description: 'Apply Pythagoras theorem',
    timeLimitSec: 300,
    grade9TargetSec: 150,
    promptIds: ['p-maths-39', 'p-maths-40', 'p-maths-41', 'p-maths-42', 'p-maths-43', 'p-maths-44', 'p-maths-45', 'p-maths-46'],
  },
  {
    id: 'maths-topic-circles',
    subjectId: 'maths',
    scopeType: 'topic',
    topicId: 'maths-t6',
    unitId: 'maths-u3',
    title: 'Circle Theorems',
    description: 'Master circle theorem facts',
    timeLimitSec: 180,
    grade9TargetSec: 90,
    promptIds: ['p-maths-47', 'p-maths-48', 'p-maths-49', 'p-maths-50', 'p-maths-51', 'p-maths-52'],
  },
  {
    id: 'maths-unit-number',
    subjectId: 'maths',
    scopeType: 'unit',
    unitId: 'maths-u1',
    title: 'Number Unit Test',
    description: 'All topics from Number unit',
    timeLimitSec: 600,
    grade9TargetSec: 300,
    promptIds: ['p-maths-1', 'p-maths-2', 'p-maths-3', 'p-maths-4', 'p-maths-5', 'p-maths-11', 'p-maths-12', 'p-maths-13', 'p-maths-14', 'p-maths-15', 'p-maths-16', 'p-maths-17', 'p-maths-18', 'p-maths-19', 'p-maths-20'],
  },
  {
    id: 'maths-unit-algebra',
    subjectId: 'maths',
    scopeType: 'unit',
    unitId: 'maths-u2',
    title: 'Algebra Unit Test',
    description: 'All topics from Algebra unit',
    timeLimitSec: 720,
    grade9TargetSec: 360,
    promptIds: ['p-maths-21', 'p-maths-22', 'p-maths-23', 'p-maths-24', 'p-maths-25', 'p-maths-26', 'p-maths-27', 'p-maths-28', 'p-maths-29', 'p-maths-30', 'p-maths-31', 'p-maths-32', 'p-maths-33', 'p-maths-34', 'p-maths-35'],
  },
  {
    id: 'maths-unit-geometry',
    subjectId: 'maths',
    scopeType: 'unit',
    unitId: 'maths-u3',
    title: 'Geometry Unit Test',
    description: 'All topics from Geometry unit',
    timeLimitSec: 600,
    grade9TargetSec: 300,
    promptIds: ['p-maths-39', 'p-maths-40', 'p-maths-41', 'p-maths-42', 'p-maths-43', 'p-maths-44', 'p-maths-47', 'p-maths-48', 'p-maths-49', 'p-maths-50', 'p-maths-51', 'p-maths-52'],
  },
  {
    id: 'maths-full',
    subjectId: 'maths',
    scopeType: 'full',
    title: 'Mathematics Full GCSE',
    description: 'Complete Mathematics challenge across all topics',
    timeLimitSec: 1800,
    grade9TargetSec: 900,
    promptIds: ['p-maths-1', 'p-maths-5', 'p-maths-10', 'p-maths-11', 'p-maths-15', 'p-maths-19', 'p-maths-21', 'p-maths-24', 'p-maths-28', 'p-maths-31', 'p-maths-35', 'p-maths-39', 'p-maths-42', 'p-maths-45', 'p-maths-47', 'p-maths-50'],
  },

  {
    id: 'bio-topic-cellstruct',
    subjectId: 'biology',
    scopeType: 'topic',
    topicId: 'bio-t1',
    unitId: 'bio-u1',
    title: 'Cell Structure Essentials',
    description: 'Master cell organelles and functions',
    timeLimitSec: 240,
    grade9TargetSec: 120,
    promptIds: ['p-bio-1', 'p-bio-2', 'p-bio-3', 'p-bio-4', 'p-bio-5', 'p-bio-6', 'p-bio-7', 'p-bio-8', 'p-bio-9', 'p-bio-10'],
  },
  {
    id: 'bio-topic-celldivision',
    subjectId: 'biology',
    scopeType: 'topic',
    topicId: 'bio-t2',
    unitId: 'bio-u1',
    title: 'Cell Division Sprint',
    description: 'Mitosis and meiosis key facts',
    timeLimitSec: 300,
    grade9TargetSec: 150,
    promptIds: ['p-bio-11', 'p-bio-12', 'p-bio-13', 'p-bio-14', 'p-bio-15', 'p-bio-16', 'p-bio-17', 'p-bio-18', 'p-bio-19', 'p-bio-20'],
  },
  {
    id: 'bio-topic-digestive',
    subjectId: 'biology',
    scopeType: 'topic',
    topicId: 'bio-t3',
    unitId: 'bio-u2',
    title: 'Digestive System Quick Fire',
    description: 'Enzymes and digestion',
    timeLimitSec: 300,
    grade9TargetSec: 150,
    promptIds: ['p-bio-21', 'p-bio-22', 'p-bio-23', 'p-bio-24', 'p-bio-25', 'p-bio-26', 'p-bio-27', 'p-bio-28', 'p-bio-29', 'p-bio-30'],
  },
  {
    id: 'bio-topic-blood',
    subjectId: 'biology',
    scopeType: 'topic',
    topicId: 'bio-t4',
    unitId: 'bio-u2',
    title: 'Blood & Circulation',
    description: 'Heart and blood vessels',
    timeLimitSec: 300,
    grade9TargetSec: 150,
    promptIds: ['p-bio-31', 'p-bio-32', 'p-bio-33', 'p-bio-34', 'p-bio-35', 'p-bio-36', 'p-bio-37', 'p-bio-38', 'p-bio-39', 'p-bio-40'],
  },
  {
    id: 'bio-topic-pathogens',
    subjectId: 'biology',
    scopeType: 'topic',
    topicId: 'bio-t5',
    unitId: 'bio-u3',
    title: 'Pathogens Essentials',
    description: 'Types of pathogens and spread',
    timeLimitSec: 240,
    grade9TargetSec: 120,
    promptIds: ['p-bio-41', 'p-bio-42', 'p-bio-43', 'p-bio-44', 'p-bio-45', 'p-bio-46', 'p-bio-47', 'p-bio-48'],
  },
  {
    id: 'bio-topic-immune',
    subjectId: 'biology',
    scopeType: 'topic',
    topicId: 'bio-t6',
    unitId: 'bio-u3',
    title: 'Immune System Drill',
    description: 'White blood cells and immunity',
    timeLimitSec: 240,
    grade9TargetSec: 120,
    promptIds: ['p-bio-49', 'p-bio-50', 'p-bio-51', 'p-bio-52', 'p-bio-53', 'p-bio-54', 'p-bio-55', 'p-bio-56'],
  },
  {
    id: 'bio-unit-cellbiology',
    subjectId: 'biology',
    scopeType: 'unit',
    unitId: 'bio-u1',
    title: 'Cell Biology Unit Test',
    description: 'All Cell Biology topics',
    timeLimitSec: 600,
    grade9TargetSec: 300,
    promptIds: ['p-bio-1', 'p-bio-3', 'p-bio-4', 'p-bio-5', 'p-bio-7', 'p-bio-9', 'p-bio-11', 'p-bio-12', 'p-bio-13', 'p-bio-15', 'p-bio-16', 'p-bio-17', 'p-bio-18'],
  },
  {
    id: 'bio-unit-organisation',
    subjectId: 'biology',
    scopeType: 'unit',
    unitId: 'bio-u2',
    title: 'Organisation Unit Test',
    description: 'All Organisation topics',
    timeLimitSec: 720,
    grade9TargetSec: 360,
    promptIds: ['p-bio-21', 'p-bio-22', 'p-bio-23', 'p-bio-24', 'p-bio-27', 'p-bio-28', 'p-bio-31', 'p-bio-32', 'p-bio-33', 'p-bio-34', 'p-bio-36', 'p-bio-37', 'p-bio-39', 'p-bio-40'],
  },
  {
    id: 'bio-unit-infection',
    subjectId: 'biology',
    scopeType: 'unit',
    unitId: 'bio-u3',
    title: 'Infection & Response Unit Test',
    description: 'All Infection topics',
    timeLimitSec: 600,
    grade9TargetSec: 300,
    promptIds: ['p-bio-41', 'p-bio-42', 'p-bio-43', 'p-bio-44', 'p-bio-46', 'p-bio-49', 'p-bio-50', 'p-bio-51', 'p-bio-52', 'p-bio-53', 'p-bio-54', 'p-bio-55'],
  },
  {
    id: 'bio-full',
    subjectId: 'biology',
    scopeType: 'full',
    title: 'Biology Full GCSE',
    description: 'Complete Biology challenge across all topics',
    timeLimitSec: 1800,
    grade9TargetSec: 900,
    promptIds: ['p-bio-1', 'p-bio-4', 'p-bio-7', 'p-bio-11', 'p-bio-13', 'p-bio-16', 'p-bio-21', 'p-bio-24', 'p-bio-28', 'p-bio-31', 'p-bio-35', 'p-bio-39', 'p-bio-42', 'p-bio-46', 'p-bio-50', 'p-bio-54'],
  },

  {
    id: 'hist-topic-weimar',
    subjectId: 'history',
    scopeType: 'topic',
    topicId: 'hist-t1',
    unitId: 'hist-u1',
    title: 'Weimar Republic Essentials',
    description: 'Early challenges 1918-1923',
    timeLimitSec: 360,
    grade9TargetSec: 180,
    promptIds: ['p-hist-1', 'p-hist-2', 'p-hist-3', 'p-hist-4', 'p-hist-5', 'p-hist-6', 'p-hist-7', 'p-hist-8', 'p-hist-9', 'p-hist-10'],
  },
  {
    id: 'hist-topic-hitler',
    subjectId: 'history',
    scopeType: 'topic',
    topicId: 'hist-t2',
    unitId: 'hist-u1',
    title: 'Hitler\'s Rise to Power',
    description: 'How Hitler became Chancellor',
    timeLimitSec: 360,
    grade9TargetSec: 180,
    promptIds: ['p-hist-11', 'p-hist-12', 'p-hist-13', 'p-hist-14', 'p-hist-15', 'p-hist-16', 'p-hist-17', 'p-hist-18', 'p-hist-19', 'p-hist-20'],
  },
  {
    id: 'hist-topic-medieval',
    subjectId: 'history',
    scopeType: 'topic',
    topicId: 'hist-t3',
    unitId: 'hist-u2',
    title: 'Medieval Medicine',
    description: 'Medical knowledge in medieval times',
    timeLimitSec: 360,
    grade9TargetSec: 180,
    promptIds: ['p-hist-21', 'p-hist-22', 'p-hist-23', 'p-hist-24', 'p-hist-25', 'p-hist-26', 'p-hist-27', 'p-hist-28'],
  },
  {
    id: 'hist-topic-renaissance',
    subjectId: 'history',
    scopeType: 'topic',
    topicId: 'hist-t4',
    unitId: 'hist-u2',
    title: 'Renaissance Medicine',
    description: 'Medical advances in Renaissance',
    timeLimitSec: 240,
    grade9TargetSec: 120,
    promptIds: ['p-hist-29', 'p-hist-30', 'p-hist-31', 'p-hist-32', 'p-hist-33', 'p-hist-34'],
  },
  {
    id: 'hist-topic-coldwarorigins',
    subjectId: 'history',
    scopeType: 'topic',
    topicId: 'hist-t5',
    unitId: 'hist-u3',
    title: 'Cold War Origins',
    description: 'How the Cold War began',
    timeLimitSec: 360,
    grade9TargetSec: 180,
    promptIds: ['p-hist-35', 'p-hist-36', 'p-hist-37', 'p-hist-38', 'p-hist-39', 'p-hist-40', 'p-hist-41', 'p-hist-42', 'p-hist-43', 'p-hist-44'],
  },
  {
    id: 'hist-topic-cuban',
    subjectId: 'history',
    scopeType: 'topic',
    topicId: 'hist-t6',
    unitId: 'hist-u3',
    title: 'Cuban Missile Crisis',
    description: 'The 1962 crisis',
    timeLimitSec: 300,
    grade9TargetSec: 150,
    promptIds: ['p-hist-45', 'p-hist-46', 'p-hist-47', 'p-hist-48', 'p-hist-49', 'p-hist-50', 'p-hist-51', 'p-hist-52'],
  },
  {
    id: 'hist-unit-nazi',
    subjectId: 'history',
    scopeType: 'unit',
    unitId: 'hist-u1',
    title: 'Weimar & Nazi Germany Unit Test',
    description: 'All Weimar & Nazi topics',
    timeLimitSec: 900,
    grade9TargetSec: 450,
    promptIds: ['p-hist-1', 'p-hist-2', 'p-hist-5', 'p-hist-7', 'p-hist-9', 'p-hist-11', 'p-hist-12', 'p-hist-15', 'p-hist-16', 'p-hist-17', 'p-hist-18', 'p-hist-19'],
  },
  {
    id: 'hist-unit-medicine',
    subjectId: 'history',
    scopeType: 'unit',
    unitId: 'hist-u2',
    title: 'Medicine Through Time Unit Test',
    description: 'All Medicine topics',
    timeLimitSec: 720,
    grade9TargetSec: 360,
    promptIds: ['p-hist-21', 'p-hist-22', 'p-hist-23', 'p-hist-25', 'p-hist-27', 'p-hist-29', 'p-hist-30', 'p-hist-31', 'p-hist-32', 'p-hist-33'],
  },
  {
    id: 'hist-unit-coldwar',
    subjectId: 'history',
    scopeType: 'unit',
    unitId: 'hist-u3',
    title: 'Cold War Unit Test',
    description: 'All Cold War topics',
    timeLimitSec: 720,
    grade9TargetSec: 360,
    promptIds: ['p-hist-35', 'p-hist-36', 'p-hist-37', 'p-hist-39', 'p-hist-41', 'p-hist-43', 'p-hist-45', 'p-hist-46', 'p-hist-47', 'p-hist-49', 'p-hist-50'],
  },
  {
    id: 'hist-full',
    subjectId: 'history',
    scopeType: 'full',
    title: 'History Full GCSE',
    description: 'Complete History challenge across all topics',
    timeLimitSec: 1800,
    grade9TargetSec: 900,
    promptIds: ['p-hist-1', 'p-hist-5', 'p-hist-9', 'p-hist-11', 'p-hist-15', 'p-hist-18', 'p-hist-21', 'p-hist-25', 'p-hist-29', 'p-hist-32', 'p-hist-35', 'p-hist-39', 'p-hist-43', 'p-hist-45', 'p-hist-49'],
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  { id: '1', name: 'Emma Johnson', avatar: '🎯', rank: 1, weeklyXP: 2450, streak: 12, readinessPercent: 87 },
  { id: '2', name: 'You', avatar: '⭐', rank: 2, weeklyXP: 2100, streak: 7, readinessPercent: 73 },
  { id: '3', name: 'Liam Smith', avatar: '🚀', rank: 3, weeklyXP: 1980, streak: 5, readinessPercent: 69 },
  { id: '4', name: 'Olivia Brown', avatar: '💪', rank: 4, weeklyXP: 1750, streak: 9, readinessPercent: 78 },
  { id: '5', name: 'Noah Wilson', avatar: '🔥', rank: 5, weeklyXP: 1620, streak: 3, readinessPercent: 65 },
  { id: '6', name: 'Ava Davis', avatar: '⚡', rank: 6, weeklyXP: 1540, streak: 6, readinessPercent: 71 },
  { id: '7', name: 'James Taylor', avatar: '🎓', rank: 7, weeklyXP: 1420, streak: 4, readinessPercent: 68 },
  { id: '8', name: 'Sophia Martinez', avatar: '✨', rank: 8, weeklyXP: 1350, streak: 8, readinessPercent: 75 },
];
