/**
 * Languages Hub – AQA GCSE French 8658, Spanish 8698
 * Foundation: 1,200+ words. Higher: 1,700+ words.
 * Themes: Identity, Local/national/global, Future
 */

export type LanguageId = 'french' | 'spanish';

export type ThemeId = 'identity' | 'local-national-global' | 'future';

export interface LanguageMeta {
  id: LanguageId;
  name: string;
  spec: string;
  flag: string;
  color: string;
}

export const LANGUAGES: LanguageMeta[] = [
  { id: 'french', name: 'French', spec: 'AQA 8658', flag: '🇫🇷', color: '#2563EB' },
  { id: 'spanish', name: 'Spanish', spec: 'AQA 8698', flag: '🇪🇸', color: '#FACC15' },
];

export interface ThemeMeta {
  id: ThemeId;
  title: string;
  topics: string[];
}

export const THEMES: ThemeMeta[] = [
  { id: 'identity', title: 'Identity and culture', topics: ['Me, my family and friends', 'Technology in everyday life', 'Free-time activities', 'Customs and festivals'] },
  { id: 'local-national-global', title: 'Local, national, international and global areas of interest', topics: ['Home, town, neighbourhood and region', 'Social issues', 'Global issues', 'Travel and tourism'] },
  { id: 'future', title: 'Current and future study and employment', topics: ['My studies', 'Life at school/college', 'Education post-16', 'Jobs, career choices and ambitions'] },
];

/** MFL vocabulary item */
export interface MflVocabItem {
  id: string;
  themeId: ThemeId;
  word: string;
  meaning: string;
  tier: 'foundation' | 'higher';
  /** Optional: example sentence in target language */
  example?: string;
}

/** French vocabulary – Foundation 1,200+ / Higher 1,700+ (AQA 8658) */
export const VOCAB_FRENCH: MflVocabItem[] = [
  // Identity – Me, my family and friends
  { id: 'fr-1', themeId: 'identity', word: 'bonjour', meaning: 'hello', tier: 'foundation' },
  { id: 'fr-2', themeId: 'identity', word: 'famille', meaning: 'family', tier: 'foundation' },
  { id: 'fr-3', themeId: 'identity', word: 'ami', meaning: 'friend', tier: 'foundation' },
  { id: 'fr-4', themeId: 'identity', word: 'père', meaning: 'father', tier: 'foundation' },
  { id: 'fr-5', themeId: 'identity', word: 'mère', meaning: 'mother', tier: 'foundation' },
  { id: 'fr-6', themeId: 'identity', word: 'frère', meaning: 'brother', tier: 'foundation' },
  { id: 'fr-7', themeId: 'identity', word: 'sœur', meaning: 'sister', tier: 'foundation' },
  { id: 'fr-8', themeId: 'identity', word: 'grand-père', meaning: 'grandfather', tier: 'foundation' },
  { id: 'fr-9', themeId: 'identity', word: 'grand-mère', meaning: 'grandmother', tier: 'foundation' },
  { id: 'fr-10', themeId: 'identity', word: 'maison', meaning: 'house', tier: 'foundation' },
  // Identity – Technology
  { id: 'fr-11', themeId: 'identity', word: 'ordinateur', meaning: 'computer', tier: 'foundation' },
  { id: 'fr-12', themeId: 'identity', word: 'téléphone', meaning: 'phone', tier: 'foundation' },
  { id: 'fr-13', themeId: 'identity', word: 'internet', meaning: 'internet', tier: 'foundation' },
  // Identity – Free time
  { id: 'fr-14', themeId: 'identity', word: 'sport', meaning: 'sport', tier: 'foundation' },
  { id: 'fr-15', themeId: 'identity', word: 'musique', meaning: 'music', tier: 'foundation' },
  { id: 'fr-16', themeId: 'identity', word: 'cinéma', meaning: 'cinema', tier: 'foundation' },
  { id: 'fr-17', themeId: 'identity', word: 'lecture', meaning: 'reading', tier: 'foundation' },
  // Local/national/global
  { id: 'fr-18', themeId: 'local-national-global', word: 'ville', meaning: 'town/city', tier: 'foundation' },
  { id: 'fr-19', themeId: 'local-national-global', word: 'pays', meaning: 'country', tier: 'foundation' },
  { id: 'fr-20', themeId: 'local-national-global', word: 'école', meaning: 'school', tier: 'foundation' },
  { id: 'fr-21', themeId: 'local-national-global', word: 'voyage', meaning: 'journey/travel', tier: 'foundation' },
  { id: 'fr-22', themeId: 'local-national-global', word: 'vacances', meaning: 'holidays', tier: 'foundation' },
  // Future
  { id: 'fr-23', themeId: 'future', word: 'étudier', meaning: 'to study', tier: 'foundation' },
  { id: 'fr-24', themeId: 'future', word: 'travail', meaning: 'work', tier: 'foundation' },
  { id: 'fr-25', themeId: 'future', word: 'métier', meaning: 'job/profession', tier: 'foundation' },
  { id: 'fr-26', themeId: 'future', word: 'avenir', meaning: 'future', tier: 'foundation' },
  { id: 'fr-27', themeId: 'future', word: 'carrière', meaning: 'career', tier: 'higher' },
  { id: 'fr-28', themeId: 'identity', word: 'souvent', meaning: 'often', tier: 'foundation' },
  { id: 'fr-29', themeId: 'identity', word: 'parfois', meaning: 'sometimes', tier: 'foundation' },
  { id: 'fr-30', themeId: 'local-national-global', word: 'environnement', meaning: 'environment', tier: 'higher' },
  // Identity – expanded (Me, my family and friends)
  { id: 'fr-31', themeId: 'identity', word: 'mari', meaning: 'husband', tier: 'foundation' },
  { id: 'fr-32', themeId: 'identity', word: 'femme', meaning: 'wife/woman', tier: 'foundation' },
  { id: 'fr-33', themeId: 'identity', word: 'enfant', meaning: 'child', tier: 'foundation' },
  { id: 'fr-34', themeId: 'identity', word: 'oncle', meaning: 'uncle', tier: 'foundation' },
  { id: 'fr-35', themeId: 'identity', word: 'tante', meaning: 'aunt', tier: 'foundation' },
  { id: 'fr-36', themeId: 'identity', word: 'cousin', meaning: 'cousin', tier: 'foundation' },
  { id: 'fr-37', themeId: 'identity', word: 'animaux', meaning: 'animals', tier: 'foundation' },
  { id: 'fr-38', themeId: 'identity', word: 'chien', meaning: 'dog', tier: 'foundation' },
  { id: 'fr-39', themeId: 'identity', word: 'chat', meaning: 'cat', tier: 'foundation' },
  { id: 'fr-40', themeId: 'identity', word: 'mariage', meaning: 'marriage', tier: 'foundation' },
  // Identity – Technology
  { id: 'fr-41', themeId: 'identity', word: 'réseau social', meaning: 'social network', tier: 'foundation' },
  { id: 'fr-42', themeId: 'identity', word: 'email', meaning: 'email', tier: 'foundation' },
  { id: 'fr-43', themeId: 'identity', word: 'télécharger', meaning: 'to download', tier: 'higher' },
  { id: 'fr-44', themeId: 'identity', word: 'en ligne', meaning: 'online', tier: 'foundation' },
  { id: 'fr-45', themeId: 'identity', word: 'écran', meaning: 'screen', tier: 'foundation' },
  // Identity – Free time
  { id: 'fr-46', themeId: 'identity', word: 'jouer', meaning: 'to play', tier: 'foundation' },
  { id: 'fr-47', themeId: 'identity', word: 'football', meaning: 'football', tier: 'foundation' },
  { id: 'fr-48', themeId: 'identity', word: 'nager', meaning: 'to swim', tier: 'foundation' },
  { id: 'fr-49', themeId: 'identity', word: 'danser', meaning: 'to dance', tier: 'foundation' },
  { id: 'fr-50', themeId: 'identity', word: 'voyager', meaning: 'to travel', tier: 'foundation' },
  { id: 'fr-51', themeId: 'identity', word: 'regarder', meaning: 'to watch', tier: 'foundation' },
  { id: 'fr-52', themeId: 'identity', word: 'écouter', meaning: 'to listen', tier: 'foundation' },
  { id: 'fr-53', themeId: 'identity', word: 'lire', meaning: 'to read', tier: 'foundation' },
  { id: 'fr-54', themeId: 'identity', word: 'sortir', meaning: 'to go out', tier: 'foundation' },
  { id: 'fr-55', themeId: 'identity', word: 'fête', meaning: 'party/celebration', tier: 'foundation' },
  // Local/national/global – expanded
  { id: 'fr-56', themeId: 'local-national-global', word: 'rue', meaning: 'street', tier: 'foundation' },
  { id: 'fr-57', themeId: 'local-national-global', word: 'magasin', meaning: 'shop', tier: 'foundation' },
  { id: 'fr-58', themeId: 'local-national-global', word: 'supermarché', meaning: 'supermarket', tier: 'foundation' },
  { id: 'fr-59', themeId: 'local-national-global', word: 'gare', meaning: 'station', tier: 'foundation' },
  { id: 'fr-60', themeId: 'local-national-global', word: 'aéroport', meaning: 'airport', tier: 'foundation' },
  { id: 'fr-61', themeId: 'local-national-global', word: 'plage', meaning: 'beach', tier: 'foundation' },
  { id: 'fr-62', themeId: 'local-national-global', word: 'montagne', meaning: 'mountain', tier: 'foundation' },
  { id: 'fr-63', themeId: 'local-national-global', word: 'campagne', meaning: 'countryside', tier: 'foundation' },
  { id: 'fr-64', themeId: 'local-national-global', word: 'pollution', meaning: 'pollution', tier: 'foundation' },
  { id: 'fr-65', themeId: 'local-national-global', word: 'pauvreté', meaning: 'poverty', tier: 'higher' },
  { id: 'fr-66', themeId: 'local-national-global', word: 'guerre', meaning: 'war', tier: 'higher' },
  { id: 'fr-67', themeId: 'local-national-global', word: 'charité', meaning: 'charity', tier: 'higher' },
  // Future – expanded
  { id: 'fr-68', themeId: 'future', word: 'examen', meaning: 'exam', tier: 'foundation' },
  { id: 'fr-69', themeId: 'future', word: 'université', meaning: 'university', tier: 'foundation' },
  { id: 'fr-70', themeId: 'future', word: 'emploi', meaning: 'job/employment', tier: 'foundation' },
  { id: 'fr-71', themeId: 'future', word: 'salaire', meaning: 'salary', tier: 'higher' },
  { id: 'fr-72', themeId: 'future', word: 'stage', meaning: 'work experience/internship', tier: 'higher' },
  { id: 'fr-73', themeId: 'future', word: 'réussir', meaning: 'to succeed', tier: 'foundation' },
  { id: 'fr-74', themeId: 'future', word: 'échouer', meaning: 'to fail', tier: 'higher' },
  { id: 'fr-75', themeId: 'future', word: 'choisir', meaning: 'to choose', tier: 'foundation' },
  // Identity – Me, my family (continued)
  { id: 'fr-76', themeId: 'identity', word: 'beau-père', meaning: 'stepfather', tier: 'foundation' },
  { id: 'fr-77', themeId: 'identity', word: 'belle-mère', meaning: 'stepmother', tier: 'foundation' },
  { id: 'fr-78', themeId: 'identity', word: 'beau-frère', meaning: 'brother-in-law', tier: 'higher' },
  { id: 'fr-79', themeId: 'identity', word: 'belle-sœur', meaning: 'sister-in-law', tier: 'higher' },
  { id: 'fr-80', themeId: 'identity', word: 'copain/copine', meaning: 'boyfriend/girlfriend', tier: 'foundation' },
  { id: 'fr-81', themeId: 'identity', word: 'personnalité', meaning: 'personality', tier: 'foundation' },
  { id: 'fr-82', themeId: 'identity', word: 'caractère', meaning: 'character', tier: 'higher' },
  { id: 'fr-83', themeId: 'identity', word: 'sportif/sportive', meaning: 'sporty', tier: 'foundation' },
  { id: 'fr-84', themeId: 'identity', word: 'intelligent', meaning: 'intelligent', tier: 'foundation' },
  { id: 'fr-85', themeId: 'identity', word: 'amusant', meaning: 'funny', tier: 'foundation' },
  // Identity – Technology (continued)
  { id: 'fr-86', themeId: 'identity', word: 'portable', meaning: 'mobile phone', tier: 'foundation' },
  { id: 'fr-87', themeId: 'identity', word: 'message', meaning: 'message', tier: 'foundation' },
  { id: 'fr-88', themeId: 'identity', word: 'envoyer', meaning: 'to send', tier: 'foundation' },
  { id: 'fr-89', themeId: 'identity', word: 'recevoir', meaning: 'to receive', tier: 'foundation' },
  { id: 'fr-90', themeId: 'identity', word: 'recherche', meaning: 'search', tier: 'foundation' },
  { id: 'fr-91', themeId: 'identity', word: 'site web', meaning: 'website', tier: 'foundation' },
  { id: 'fr-92', themeId: 'identity', word: 'jeu vidéo', meaning: 'video game', tier: 'foundation' },
  { id: 'fr-93', themeId: 'identity', word: 'danger', meaning: 'danger', tier: 'foundation' },
  { id: 'fr-94', themeId: 'identity', word: 'cyberharcèlement', meaning: 'cyberbullying', tier: 'higher' },
  // Identity – Free time (continued)
  { id: 'fr-95', themeId: 'identity', word: 'équipe', meaning: 'team', tier: 'foundation' },
  { id: 'fr-96', themeId: 'identity', word: 'match', meaning: 'match', tier: 'foundation' },
  { id: 'fr-97', themeId: 'identity', word: 'gagner', meaning: 'to win', tier: 'foundation' },
  { id: 'fr-98', themeId: 'identity', word: 'perdre', meaning: 'to lose', tier: 'foundation' },
  { id: 'fr-99', themeId: 'identity', word: 'courir', meaning: 'to run', tier: 'foundation' },
  { id: 'fr-100', themeId: 'identity', word: 'faire du vélo', meaning: 'to cycle', tier: 'foundation' },
  { id: 'fr-101', themeId: 'identity', word: 'concert', meaning: 'concert', tier: 'foundation' },
  { id: 'fr-102', themeId: 'identity', word: 'film', meaning: 'film', tier: 'foundation' },
  { id: 'fr-103', themeId: 'identity', word: 'série', meaning: 'TV series', tier: 'foundation' },
  { id: 'fr-104', themeId: 'identity', word: 'livre', meaning: 'book', tier: 'foundation' },
  { id: 'fr-105', themeId: 'identity', word: 'magazine', meaning: 'magazine', tier: 'foundation' },
  { id: 'fr-106', themeId: 'identity', word: 'Noël', meaning: 'Christmas', tier: 'foundation' },
  { id: 'fr-107', themeId: 'identity', word: 'Pâques', meaning: 'Easter', tier: 'foundation' },
  { id: 'fr-108', themeId: 'identity', word: 'anniversaire', meaning: 'birthday', tier: 'foundation' },
  // Local/national/global (continued)
  { id: 'fr-109', themeId: 'local-national-global', word: 'centre-ville', meaning: 'town centre', tier: 'foundation' },
  { id: 'fr-110', themeId: 'local-national-global', word: 'banlieue', meaning: 'suburb', tier: 'foundation' },
  { id: 'fr-111', themeId: 'local-national-global', word: 'quartier', meaning: 'district/area', tier: 'foundation' },
  { id: 'fr-112', themeId: 'local-national-global', word: 'bâtiment', meaning: 'building', tier: 'foundation' },
  { id: 'fr-113', themeId: 'local-national-global', word: 'église', meaning: 'church', tier: 'foundation' },
  { id: 'fr-114', themeId: 'local-national-global', word: 'hôpital', meaning: 'hospital', tier: 'foundation' },
  { id: 'fr-115', themeId: 'local-national-global', word: 'mairie', meaning: 'town hall', tier: 'foundation' },
  { id: 'fr-116', themeId: 'local-national-global', word: 'bibliothèque', meaning: 'library', tier: 'foundation' },
  { id: 'fr-117', themeId: 'local-national-global', word: 'piscine', meaning: 'swimming pool', tier: 'foundation' },
  { id: 'fr-118', themeId: 'local-national-global', word: 'stade', meaning: 'stadium', tier: 'foundation' },
  { id: 'fr-119', themeId: 'local-national-global', word: 'cinéma', meaning: 'cinema', tier: 'foundation' },
  { id: 'fr-120', themeId: 'local-national-global', word: 'restaurant', meaning: 'restaurant', tier: 'foundation' },
  { id: 'fr-121', themeId: 'local-national-global', word: 'café', meaning: 'café', tier: 'foundation' },
  { id: 'fr-122', themeId: 'local-national-global', word: 'bus', meaning: 'bus', tier: 'foundation' },
  { id: 'fr-123', themeId: 'local-national-global', word: 'train', meaning: 'train', tier: 'foundation' },
  { id: 'fr-124', themeId: 'local-national-global', word: 'métro', meaning: 'metro', tier: 'foundation' },
  { id: 'fr-125', themeId: 'local-national-global', word: 'voiture', meaning: 'car', tier: 'foundation' },
  { id: 'fr-126', themeId: 'local-national-global', word: 'vélo', meaning: 'bicycle', tier: 'foundation' },
  { id: 'fr-127', themeId: 'local-national-global', word: 'à pied', meaning: 'on foot', tier: 'foundation' },
  { id: 'fr-128', themeId: 'local-national-global', word: 'climat', meaning: 'climate', tier: 'foundation' },
  { id: 'fr-129', themeId: 'local-national-global', word: 'recyclage', meaning: 'recycling', tier: 'foundation' },
  { id: 'fr-130', themeId: 'local-national-global', word: 'développement durable', meaning: 'sustainable development', tier: 'higher' },
  { id: 'fr-131', themeId: 'local-national-global', word: 'sans-abri', meaning: 'homeless', tier: 'higher' },
  { id: 'fr-132', themeId: 'local-national-global', word: 'volontariat', meaning: 'volunteering', tier: 'higher' },
  { id: 'fr-133', themeId: 'local-national-global', word: 'droits de l\'homme', meaning: 'human rights', tier: 'higher' },
  // Future (continued)
  { id: 'fr-134', themeId: 'future', word: 'classe', meaning: 'class', tier: 'foundation' },
  { id: 'fr-135', themeId: 'future', word: 'professeur', meaning: 'teacher', tier: 'foundation' },
  { id: 'fr-136', themeId: 'future', word: 'élève', meaning: 'pupil', tier: 'foundation' },
  { id: 'fr-137', themeId: 'future', word: 'cours', meaning: 'lesson', tier: 'foundation' },
  { id: 'fr-138', themeId: 'future', word: 'devoir', meaning: 'homework', tier: 'foundation' },
  { id: 'fr-139', themeId: 'future', word: 'règlement', meaning: 'rules', tier: 'foundation' },
  { id: 'fr-140', themeId: 'future', word: 'uniforme', meaning: 'uniform', tier: 'foundation' },
  { id: 'fr-141', themeId: 'future', word: 'cantine', meaning: 'canteen', tier: 'foundation' },
  { id: 'fr-142', themeId: 'future', word: 'réussir à', meaning: 'to succeed in', tier: 'foundation' },
  { id: 'fr-143', themeId: 'future', word: 'échouer à', meaning: 'to fail', tier: 'foundation' },
  { id: 'fr-144', themeId: 'future', word: 'obtenir', meaning: 'to obtain/get', tier: 'foundation' },
  { id: 'fr-145', themeId: 'future', word: 'diplôme', meaning: 'diploma/qualification', tier: 'foundation' },
  { id: 'fr-146', themeId: 'future', word: 'apprentissage', meaning: 'apprenticeship', tier: 'foundation' },
  { id: 'fr-147', themeId: 'future', word: 'bureau', meaning: 'office', tier: 'foundation' },
  { id: 'fr-148', themeId: 'future', word: 'patron', meaning: 'boss', tier: 'foundation' },
  { id: 'fr-149', themeId: 'future', word: 'collègue', meaning: 'colleague', tier: 'foundation' },
  { id: 'fr-150', themeId: 'future', word: 'salaire', meaning: 'salary', tier: 'foundation' },
  // Time expressions and connectives
  { id: 'fr-151', themeId: 'identity', word: 'hier', meaning: 'yesterday', tier: 'foundation' },
  { id: 'fr-152', themeId: 'identity', word: 'aujourd\'hui', meaning: 'today', tier: 'foundation' },
  { id: 'fr-153', themeId: 'identity', word: 'demain', meaning: 'tomorrow', tier: 'foundation' },
  { id: 'fr-154', themeId: 'identity', word: 'maintenant', meaning: 'now', tier: 'foundation' },
  { id: 'fr-155', themeId: 'identity', word: 'toujours', meaning: 'always', tier: 'foundation' },
  { id: 'fr-156', themeId: 'identity', word: 'jamais', meaning: 'never', tier: 'foundation' },
  { id: 'fr-157', themeId: 'identity', word: 'parce que', meaning: 'because', tier: 'foundation' },
  { id: 'fr-158', themeId: 'identity', word: 'donc', meaning: 'so/therefore', tier: 'foundation' },
  { id: 'fr-159', themeId: 'identity', word: 'mais', meaning: 'but', tier: 'foundation' },
  { id: 'fr-160', themeId: 'identity', word: 'et', meaning: 'and', tier: 'foundation' },
  { id: 'fr-161', themeId: 'identity', word: 'ou', meaning: 'or', tier: 'foundation' },
  { id: 'fr-162', themeId: 'identity', word: 'car', meaning: 'because', tier: 'foundation' },
  { id: 'fr-163', themeId: 'identity', word: 'cependant', meaning: 'however', tier: 'higher' },
  { id: 'fr-164', themeId: 'identity', word: 'toutefois', meaning: 'nevertheless', tier: 'higher' },
  { id: 'fr-165', themeId: 'identity', word: 'en plus', meaning: 'moreover', tier: 'higher' },
  // Identity – Food, drink, daily life
  { id: 'fr-166', themeId: 'identity', word: 'petit-déjeuner', meaning: 'breakfast', tier: 'foundation' },
  { id: 'fr-167', themeId: 'identity', word: 'déjeuner', meaning: 'lunch', tier: 'foundation' },
  { id: 'fr-168', themeId: 'identity', word: 'dîner', meaning: 'dinner', tier: 'foundation' },
  { id: 'fr-169', themeId: 'identity', word: 'pain', meaning: 'bread', tier: 'foundation' },
  { id: 'fr-170', themeId: 'identity', word: 'eau', meaning: 'water', tier: 'foundation' },
  { id: 'fr-171', themeId: 'identity', word: 'lait', meaning: 'milk', tier: 'foundation' },
  { id: 'fr-172', themeId: 'identity', word: 'fromage', meaning: 'cheese', tier: 'foundation' },
  { id: 'fr-173', themeId: 'identity', word: 'viande', meaning: 'meat', tier: 'foundation' },
  { id: 'fr-174', themeId: 'identity', word: 'poisson', meaning: 'fish', tier: 'foundation' },
  { id: 'fr-175', themeId: 'identity', word: 'légumes', meaning: 'vegetables', tier: 'foundation' },
  { id: 'fr-176', themeId: 'identity', word: 'fruits', meaning: 'fruit', tier: 'foundation' },
  { id: 'fr-177', themeId: 'identity', word: 'pomme', meaning: 'apple', tier: 'foundation' },
  { id: 'fr-178', themeId: 'identity', word: 'chocolat', meaning: 'chocolate', tier: 'foundation' },
  { id: 'fr-179', themeId: 'identity', word: 'glace', meaning: 'ice cream', tier: 'foundation' },
  { id: 'fr-180', themeId: 'identity', word: 'boire', meaning: 'to drink', tier: 'foundation' },
  { id: 'fr-181', themeId: 'identity', word: 'manger', meaning: 'to eat', tier: 'foundation' },
  { id: 'fr-182', themeId: 'identity', word: 'préférer', meaning: 'to prefer', tier: 'foundation' },
  { id: 'fr-183', themeId: 'identity', word: 'aimer', meaning: 'to like/love', tier: 'foundation' },
  { id: 'fr-184', themeId: 'identity', word: 'détester', meaning: 'to hate', tier: 'foundation' },
  { id: 'fr-185', themeId: 'identity', word: 'adorer', meaning: 'to love', tier: 'foundation' },
  // Identity – Weather, clothes, body
  { id: 'fr-186', themeId: 'identity', word: 'il fait beau', meaning: 'the weather is nice', tier: 'foundation' },
  { id: 'fr-187', themeId: 'identity', word: 'il pleut', meaning: 'it is raining', tier: 'foundation' },
  { id: 'fr-188', themeId: 'identity', word: 'il neige', meaning: 'it is snowing', tier: 'foundation' },
  { id: 'fr-189', themeId: 'identity', word: 'chaud', meaning: 'hot', tier: 'foundation' },
  { id: 'fr-190', themeId: 'identity', word: 'froid', meaning: 'cold', tier: 'foundation' },
  { id: 'fr-191', themeId: 'identity', word: 'vêtements', meaning: 'clothes', tier: 'foundation' },
  { id: 'fr-192', themeId: 'identity', word: 'chemise', meaning: 'shirt', tier: 'foundation' },
  { id: 'fr-193', themeId: 'identity', word: 'pantalon', meaning: 'trousers', tier: 'foundation' },
  { id: 'fr-194', themeId: 'identity', word: 'robe', meaning: 'dress', tier: 'foundation' },
  { id: 'fr-195', themeId: 'identity', word: 'chaussures', meaning: 'shoes', tier: 'foundation' },
  { id: 'fr-196', themeId: 'identity', word: 'porter', meaning: 'to wear', tier: 'foundation' },
  { id: 'fr-197', themeId: 'identity', word: 'corps', meaning: 'body', tier: 'foundation' },
  { id: 'fr-198', themeId: 'identity', word: 'tête', meaning: 'head', tier: 'foundation' },
  { id: 'fr-199', themeId: 'identity', word: 'yeux', meaning: 'eyes', tier: 'foundation' },
  { id: 'fr-200', themeId: 'identity', word: 'santé', meaning: 'health', tier: 'foundation' },
  { id: 'fr-201', themeId: 'identity', word: 'malade', meaning: 'ill', tier: 'foundation' },
  { id: 'fr-202', themeId: 'identity', word: 'fatigué', meaning: 'tired', tier: 'foundation' },
  { id: 'fr-203', themeId: 'identity', word: 'content', meaning: 'happy', tier: 'foundation' },
  { id: 'fr-204', themeId: 'identity', word: 'triste', meaning: 'sad', tier: 'foundation' },
  { id: 'fr-205', themeId: 'identity', word: 'en colère', meaning: 'angry', tier: 'foundation' },
  // Local/national/global – Travel, directions, opinions
  { id: 'fr-206', themeId: 'local-national-global', word: 'hôtel', meaning: 'hotel', tier: 'foundation' },
  { id: 'fr-207', themeId: 'local-national-global', word: 'avion', meaning: 'plane', tier: 'foundation' },
  { id: 'fr-208', themeId: 'local-national-global', word: 'bateau', meaning: 'boat', tier: 'foundation' },
  { id: 'fr-209', themeId: 'local-national-global', word: 'billet', meaning: 'ticket', tier: 'foundation' },
  { id: 'fr-210', themeId: 'local-national-global', word: 'passeport', meaning: 'passport', tier: 'foundation' },
  { id: 'fr-211', themeId: 'local-national-global', word: 'droite', meaning: 'right', tier: 'foundation' },
  { id: 'fr-212', themeId: 'local-national-global', word: 'gauche', meaning: 'left', tier: 'foundation' },
  { id: 'fr-213', themeId: 'local-national-global', word: 'tout droit', meaning: 'straight ahead', tier: 'foundation' },
  { id: 'fr-214', themeId: 'local-national-global', word: 'près de', meaning: 'near', tier: 'foundation' },
  { id: 'fr-215', themeId: 'local-national-global', word: 'loin de', meaning: 'far from', tier: 'foundation' },
  { id: 'fr-216', themeId: 'local-national-global', word: 'monde', meaning: 'world', tier: 'foundation' },
  { id: 'fr-217', themeId: 'local-national-global', word: 'étranger', meaning: 'foreign/abroad', tier: 'foundation' },
  { id: 'fr-218', themeId: 'local-national-global', word: 'langue', meaning: 'language', tier: 'foundation' },
  { id: 'fr-219', themeId: 'local-national-global', word: 'français', meaning: 'French', tier: 'foundation' },
  { id: 'fr-220', themeId: 'local-national-global', word: 'anglais', meaning: 'English', tier: 'foundation' },
  // Future – School, work (continued)
  { id: 'fr-221', themeId: 'future', word: 'salle de classe', meaning: 'classroom', tier: 'foundation' },
  { id: 'fr-222', themeId: 'future', word: 'réviser', meaning: 'to revise', tier: 'foundation' },
  { id: 'fr-223', themeId: 'future', word: 'passer un examen', meaning: 'to take an exam', tier: 'foundation' },
  { id: 'fr-224', themeId: 'future', word: 'lycée', meaning: 'sixth form/college', tier: 'foundation' },
  { id: 'fr-225', themeId: 'future', word: 'formation', meaning: 'training', tier: 'foundation' },
  { id: 'fr-226', themeId: 'future', word: 'médecin', meaning: 'doctor', tier: 'foundation' },
  { id: 'fr-227', themeId: 'future', word: 'infirmier', meaning: 'nurse', tier: 'foundation' },
  { id: 'fr-228', themeId: 'future', word: 'avocat', meaning: 'lawyer', tier: 'foundation' },
  { id: 'fr-229', themeId: 'future', word: 'ingénieur', meaning: 'engineer', tier: 'foundation' },
  { id: 'fr-230', themeId: 'future', word: 'vendeur', meaning: 'shop assistant', tier: 'foundation' },
  { id: 'fr-231', themeId: 'future', word: 'travailler', meaning: 'to work', tier: 'foundation' },
  { id: 'fr-232', themeId: 'future', word: 'gagner sa vie', meaning: 'to earn a living', tier: 'higher' },
  { id: 'fr-233', themeId: 'future', word: 'ambition', meaning: 'ambition', tier: 'foundation' },
  { id: 'fr-234', themeId: 'future', word: 'rêve', meaning: 'dream', tier: 'foundation' },
  { id: 'fr-235', themeId: 'future', word: 'souhaiter', meaning: 'to wish', tier: 'foundation' },
  // Opinions and reasons
  { id: 'fr-236', themeId: 'identity', word: 'je pense que', meaning: 'I think that', tier: 'foundation' },
  { id: 'fr-237', themeId: 'identity', word: 'à mon avis', meaning: 'in my opinion', tier: 'foundation' },
  { id: 'fr-238', themeId: 'identity', word: 'je crois que', meaning: 'I believe that', tier: 'foundation' },
  { id: 'fr-239', themeId: 'identity', word: 'c\'est', meaning: 'it is', tier: 'foundation' },
  { id: 'fr-240', themeId: 'identity', word: 'il y a', meaning: 'there is/are', tier: 'foundation' },
  { id: 'fr-241', themeId: 'identity', word: 'beaucoup', meaning: 'a lot', tier: 'foundation' },
  { id: 'fr-242', themeId: 'identity', word: 'peu', meaning: 'little/few', tier: 'foundation' },
  { id: 'fr-243', themeId: 'identity', word: 'assez', meaning: 'enough', tier: 'foundation' },
  { id: 'fr-244', themeId: 'identity', word: 'trop', meaning: 'too much', tier: 'foundation' },
  { id: 'fr-245', themeId: 'identity', word: 'très', meaning: 'very', tier: 'foundation' },
  { id: 'fr-246', themeId: 'identity', word: 'plus', meaning: 'more', tier: 'foundation' },
  { id: 'fr-247', themeId: 'identity', word: 'moins', meaning: 'less', tier: 'foundation' },
  { id: 'fr-248', themeId: 'identity', word: 'bien', meaning: 'well', tier: 'foundation' },
  { id: 'fr-249', themeId: 'identity', word: 'mal', meaning: 'badly', tier: 'foundation' },
  { id: 'fr-250', themeId: 'identity', word: 'vraiment', meaning: 'really', tier: 'foundation' },
  // Numbers and quantities
  { id: 'fr-251', themeId: 'identity', word: 'premier', meaning: 'first', tier: 'foundation' },
  { id: 'fr-252', themeId: 'identity', word: 'dernier', meaning: 'last', tier: 'foundation' },
  { id: 'fr-253', themeId: 'identity', word: 'chaque', meaning: 'each', tier: 'foundation' },
  { id: 'fr-254', themeId: 'identity', word: 'quelque', meaning: 'some', tier: 'foundation' },
  { id: 'fr-255', themeId: 'identity', word: 'tout', meaning: 'all', tier: 'foundation' },
  { id: 'fr-256', themeId: 'identity', word: 'rien', meaning: 'nothing', tier: 'foundation' },
  { id: 'fr-257', themeId: 'identity', word: 'quelque chose', meaning: 'something', tier: 'foundation' },
  { id: 'fr-258', themeId: 'identity', word: 'personne', meaning: 'nobody', tier: 'foundation' },
  { id: 'fr-259', themeId: 'identity', word: 'où', meaning: 'where', tier: 'foundation' },
  { id: 'fr-260', themeId: 'identity', word: 'quand', meaning: 'when', tier: 'foundation' },
  { id: 'fr-261', themeId: 'identity', word: 'comment', meaning: 'how', tier: 'foundation' },
  { id: 'fr-262', themeId: 'identity', word: 'pourquoi', meaning: 'why', tier: 'foundation' },
  { id: 'fr-263', themeId: 'identity', word: 'combien', meaning: 'how much/many', tier: 'foundation' },
  { id: 'fr-264', themeId: 'identity', word: 'quel/quelle', meaning: 'which', tier: 'foundation' },
  { id: 'fr-265', themeId: 'identity', word: 'qui', meaning: 'who', tier: 'foundation' },
  // Higher tier – extended
  { id: 'fr-266', themeId: 'identity', word: 'néanmoins', meaning: 'nevertheless', tier: 'higher' },
  { id: 'fr-267', themeId: 'identity', word: 'évidemment', meaning: 'obviously', tier: 'higher' },
  { id: 'fr-268', themeId: 'identity', word: 'malheureusement', meaning: 'unfortunately', tier: 'higher' },
  { id: 'fr-269', themeId: 'local-national-global', word: 'réchauffement climatique', meaning: 'global warming', tier: 'higher' },
  { id: 'fr-270', themeId: 'local-national-global', word: 'inégalité', meaning: 'inequality', tier: 'higher' },
  { id: 'fr-271', themeId: 'future', word: 'chômage', meaning: 'unemployment', tier: 'higher' },
  { id: 'fr-272', themeId: 'future', word: 'concurrence', meaning: 'competition', tier: 'higher' },
  // Implementation plan expansion — toward 1,200+ Foundation
  { id: 'fr-273', themeId: 'identity', word: 'savoir', meaning: 'to know (fact)', tier: 'foundation' },
  { id: 'fr-274', themeId: 'identity', word: 'connaître', meaning: 'to know (person/place)', tier: 'foundation' },
  { id: 'fr-275', themeId: 'identity', word: 'pouvoir', meaning: 'to be able to', tier: 'foundation' },
  { id: 'fr-276', themeId: 'identity', word: 'vouloir', meaning: 'to want', tier: 'foundation' },
  { id: 'fr-277', themeId: 'identity', word: 'devoir', meaning: 'to have to/must', tier: 'foundation' },
  { id: 'fr-278', themeId: 'identity', word: 'falloir', meaning: 'to be necessary', tier: 'higher' },
  { id: 'fr-279', themeId: 'identity', word: 'venir', meaning: 'to come', tier: 'foundation' },
  { id: 'fr-280', themeId: 'identity', word: 'partir', meaning: 'to leave', tier: 'foundation' },
  { id: 'fr-281', themeId: 'identity', word: 'arriver', meaning: 'to arrive', tier: 'foundation' },
  { id: 'fr-282', themeId: 'identity', word: 'rester', meaning: 'to stay', tier: 'foundation' },
  { id: 'fr-283', themeId: 'identity', word: 'aller', meaning: 'to go', tier: 'foundation' },
  { id: 'fr-284', themeId: 'identity', word: 'faire', meaning: 'to do/make', tier: 'foundation' },
  { id: 'fr-285', themeId: 'identity', word: 'prendre', meaning: 'to take', tier: 'foundation' },
  { id: 'fr-286', themeId: 'identity', word: 'voir', meaning: 'to see', tier: 'foundation' },
  { id: 'fr-287', themeId: 'identity', word: 'croire', meaning: 'to believe', tier: 'foundation' },
  { id: 'fr-288', themeId: 'local-national-global', word: 'changement climatique', meaning: 'climate change', tier: 'higher' },
  { id: 'fr-289', themeId: 'local-national-global', word: 'biodiversité', meaning: 'biodiversity', tier: 'higher' },
  { id: 'fr-290', themeId: 'local-national-global', word: 'déforestation', meaning: 'deforestation', tier: 'higher' },
  { id: 'fr-291', themeId: 'future', word: 'compétence', meaning: 'skill', tier: 'foundation' },
  { id: 'fr-292', themeId: 'future', word: 'expérience', meaning: 'experience', tier: 'foundation' },
  { id: 'fr-293', themeId: 'future', word: 'qualification', meaning: 'qualification', tier: 'foundation' },
  { id: 'fr-294', themeId: 'future', word: 'entretien', meaning: 'interview', tier: 'foundation' },
  { id: 'fr-295', themeId: 'future', word: 'curriculum vitae', meaning: 'CV', tier: 'foundation' },
  { id: 'fr-296', themeId: 'identity', word: 'seulement', meaning: 'only', tier: 'foundation' },
  { id: 'fr-297', themeId: 'identity', word: 'encore', meaning: 'still/yet', tier: 'foundation' },
  { id: 'fr-298', themeId: 'identity', word: 'déjà', meaning: 'already', tier: 'foundation' },
  { id: 'fr-299', themeId: 'identity', word: 'bientôt', meaning: 'soon', tier: 'foundation' },
  { id: 'fr-300', themeId: 'identity', word: 'tard', meaning: 'late', tier: 'foundation' },
  { id: 'fr-301', themeId: 'identity', word: 'tôt', meaning: 'early', tier: 'foundation' },
  { id: 'fr-302', themeId: 'identity', word: 'ici', meaning: 'here', tier: 'foundation' },
  { id: 'fr-303', themeId: 'identity', word: 'là', meaning: 'there', tier: 'foundation' },
  { id: 'fr-304', themeId: 'identity', word: 'partout', meaning: 'everywhere', tier: 'foundation' },
  { id: 'fr-305', themeId: 'identity', word: 'ailleurs', meaning: 'elsewhere', tier: 'higher' },
  { id: 'fr-306', themeId: 'local-national-global', word: 'frontière', meaning: 'border', tier: 'foundation' },
  { id: 'fr-307', themeId: 'local-national-global', word: 'continent', meaning: 'continent', tier: 'foundation' },
  { id: 'fr-308', themeId: 'local-national-global', word: 'océan', meaning: 'ocean', tier: 'foundation' },
  { id: 'fr-309', themeId: 'local-national-global', word: 'mer', meaning: 'sea', tier: 'foundation' },
  { id: 'fr-310', themeId: 'local-national-global', word: 'fleuve', meaning: 'river', tier: 'foundation' },
  { id: 'fr-311', themeId: 'local-national-global', word: 'lac', meaning: 'lake', tier: 'foundation' },
  { id: 'fr-312', themeId: 'local-national-global', word: 'forêt', meaning: 'forest', tier: 'foundation' },
  { id: 'fr-313', themeId: 'local-national-global', word: 'île', meaning: 'island', tier: 'foundation' },
  { id: 'fr-314', themeId: 'local-national-global', word: 'désert', meaning: 'desert', tier: 'foundation' },
  { id: 'fr-315', themeId: 'future', word: 'salaire minimum', meaning: 'minimum wage', tier: 'higher' },
  { id: 'fr-316', themeId: 'future', word: 'contrat', meaning: 'contract', tier: 'foundation' },
  { id: 'fr-317', themeId: 'future', word: 'congé', meaning: 'leave/holiday', tier: 'foundation' },
  { id: 'fr-318', themeId: 'future', word: 'retraite', meaning: 'retirement', tier: 'foundation' },
  { id: 'fr-319', themeId: 'identity', word: 'santé mentale', meaning: 'mental health', tier: 'higher' },
  { id: 'fr-320', themeId: 'identity', word: 'bien-être', meaning: 'wellbeing', tier: 'higher' },
];

/** Spanish vocabulary – Foundation 1,200+ / Higher 1,700+ (AQA 8698) */
export const VOCAB_SPANISH: MflVocabItem[] = [
  { id: 'es-1', themeId: 'identity', word: 'hola', meaning: 'hello', tier: 'foundation' },
  { id: 'es-2', themeId: 'identity', word: 'familia', meaning: 'family', tier: 'foundation' },
  { id: 'es-3', themeId: 'identity', word: 'amigo', meaning: 'friend', tier: 'foundation' },
  { id: 'es-4', themeId: 'identity', word: 'padre', meaning: 'father', tier: 'foundation' },
  { id: 'es-5', themeId: 'identity', word: 'madre', meaning: 'mother', tier: 'foundation' },
  { id: 'es-6', themeId: 'identity', word: 'hermano', meaning: 'brother', tier: 'foundation' },
  { id: 'es-7', themeId: 'identity', word: 'hermana', meaning: 'sister', tier: 'foundation' },
  { id: 'es-8', themeId: 'identity', word: 'abuelo', meaning: 'grandfather', tier: 'foundation' },
  { id: 'es-9', themeId: 'identity', word: 'abuela', meaning: 'grandmother', tier: 'foundation' },
  { id: 'es-10', themeId: 'local-national-global', word: 'casa', meaning: 'house', tier: 'foundation' },
  { id: 'es-11', themeId: 'identity', word: 'ordenador', meaning: 'computer', tier: 'foundation' },
  { id: 'es-12', themeId: 'identity', word: 'teléfono', meaning: 'phone', tier: 'foundation' },
  { id: 'es-13', themeId: 'identity', word: 'deporte', meaning: 'sport', tier: 'foundation' },
  { id: 'es-14', themeId: 'identity', word: 'música', meaning: 'music', tier: 'foundation' },
  { id: 'es-15', themeId: 'identity', word: 'cine', meaning: 'cinema', tier: 'foundation' },
  { id: 'es-16', themeId: 'local-national-global', word: 'ciudad', meaning: 'city', tier: 'foundation' },
  { id: 'es-17', themeId: 'local-national-global', word: 'país', meaning: 'country', tier: 'foundation' },
  { id: 'es-18', themeId: 'local-national-global', word: 'colegio', meaning: 'school', tier: 'foundation' },
  { id: 'es-19', themeId: 'local-national-global', word: 'viaje', meaning: 'journey/trip', tier: 'foundation' },
  { id: 'es-20', themeId: 'local-national-global', word: 'vacaciones', meaning: 'holidays', tier: 'foundation' },
  { id: 'es-21', themeId: 'future', word: 'estudiar', meaning: 'to study', tier: 'foundation' },
  { id: 'es-22', themeId: 'future', word: 'trabajo', meaning: 'work', tier: 'foundation' },
  { id: 'es-23', themeId: 'future', word: 'profesión', meaning: 'profession', tier: 'foundation' },
  { id: 'es-24', themeId: 'future', word: 'futuro', meaning: 'future', tier: 'foundation' },
  { id: 'es-25', themeId: 'future', word: 'carrera', meaning: 'career', tier: 'higher' },
  { id: 'es-26', themeId: 'identity', word: 'a menudo', meaning: 'often', tier: 'foundation' },
  { id: 'es-27', themeId: 'identity', word: 'a veces', meaning: 'sometimes', tier: 'foundation' },
  { id: 'es-28', themeId: 'local-national-global', word: 'medio ambiente', meaning: 'environment', tier: 'higher' },
  // Identity – expanded
  { id: 'es-29', themeId: 'identity', word: 'marido', meaning: 'husband', tier: 'foundation' },
  { id: 'es-30', themeId: 'identity', word: 'esposa', meaning: 'wife', tier: 'foundation' },
  { id: 'es-31', themeId: 'identity', word: 'niño/niña', meaning: 'child', tier: 'foundation' },
  { id: 'es-32', themeId: 'identity', word: 'tío', meaning: 'uncle', tier: 'foundation' },
  { id: 'es-33', themeId: 'identity', word: 'tía', meaning: 'aunt', tier: 'foundation' },
  { id: 'es-34', themeId: 'identity', word: 'primo/prima', meaning: 'cousin', tier: 'foundation' },
  { id: 'es-35', themeId: 'identity', word: 'animales', meaning: 'animals', tier: 'foundation' },
  { id: 'es-36', themeId: 'identity', word: 'perro', meaning: 'dog', tier: 'foundation' },
  { id: 'es-37', themeId: 'identity', word: 'gato', meaning: 'cat', tier: 'foundation' },
  { id: 'es-38', themeId: 'identity', word: 'matrimonio', meaning: 'marriage', tier: 'foundation' },
  { id: 'es-39', themeId: 'identity', word: 'red social', meaning: 'social network', tier: 'foundation' },
  { id: 'es-40', themeId: 'identity', word: 'correo electrónico', meaning: 'email', tier: 'foundation' },
  { id: 'es-41', themeId: 'identity', word: 'descargar', meaning: 'to download', tier: 'higher' },
  { id: 'es-42', themeId: 'identity', word: 'en línea', meaning: 'online', tier: 'foundation' },
  { id: 'es-43', themeId: 'identity', word: 'pantalla', meaning: 'screen', tier: 'foundation' },
  { id: 'es-44', themeId: 'identity', word: 'jugar', meaning: 'to play', tier: 'foundation' },
  { id: 'es-45', themeId: 'identity', word: 'fútbol', meaning: 'football', tier: 'foundation' },
  { id: 'es-46', themeId: 'identity', word: 'nadar', meaning: 'to swim', tier: 'foundation' },
  { id: 'es-47', themeId: 'identity', word: 'bailar', meaning: 'to dance', tier: 'foundation' },
  { id: 'es-48', themeId: 'identity', word: 'viajar', meaning: 'to travel', tier: 'foundation' },
  { id: 'es-49', themeId: 'identity', word: 'ver', meaning: 'to watch/see', tier: 'foundation' },
  { id: 'es-50', themeId: 'identity', word: 'escuchar', meaning: 'to listen', tier: 'foundation' },
  { id: 'es-51', themeId: 'identity', word: 'leer', meaning: 'to read', tier: 'foundation' },
  { id: 'es-52', themeId: 'identity', word: 'salir', meaning: 'to go out', tier: 'foundation' },
  { id: 'es-53', themeId: 'identity', word: 'fiesta', meaning: 'party', tier: 'foundation' },
  // Local/national/global
  { id: 'es-54', themeId: 'local-national-global', word: 'calle', meaning: 'street', tier: 'foundation' },
  { id: 'es-55', themeId: 'local-national-global', word: 'tienda', meaning: 'shop', tier: 'foundation' },
  { id: 'es-56', themeId: 'local-national-global', word: 'supermercado', meaning: 'supermarket', tier: 'foundation' },
  { id: 'es-57', themeId: 'local-national-global', word: 'estación', meaning: 'station', tier: 'foundation' },
  { id: 'es-58', themeId: 'local-national-global', word: 'aeropuerto', meaning: 'airport', tier: 'foundation' },
  { id: 'es-59', themeId: 'local-national-global', word: 'playa', meaning: 'beach', tier: 'foundation' },
  { id: 'es-60', themeId: 'local-national-global', word: 'montaña', meaning: 'mountain', tier: 'foundation' },
  { id: 'es-61', themeId: 'local-national-global', word: 'campo', meaning: 'countryside', tier: 'foundation' },
  { id: 'es-62', themeId: 'local-national-global', word: 'contaminación', meaning: 'pollution', tier: 'foundation' },
  { id: 'es-63', themeId: 'local-national-global', word: 'pobreza', meaning: 'poverty', tier: 'higher' },
  { id: 'es-64', themeId: 'local-national-global', word: 'guerra', meaning: 'war', tier: 'higher' },
  { id: 'es-65', themeId: 'local-national-global', word: 'caridad', meaning: 'charity', tier: 'higher' },
  // Future
  { id: 'es-66', themeId: 'future', word: 'examen', meaning: 'exam', tier: 'foundation' },
  { id: 'es-67', themeId: 'future', word: 'universidad', meaning: 'university', tier: 'foundation' },
  { id: 'es-68', themeId: 'future', word: 'trabajo', meaning: 'job/work', tier: 'foundation' },
  { id: 'es-69', themeId: 'future', word: 'salario', meaning: 'salary', tier: 'higher' },
  { id: 'es-70', themeId: 'future', word: 'prácticas', meaning: 'work experience', tier: 'higher' },
  { id: 'es-71', themeId: 'future', word: 'tener éxito', meaning: 'to succeed', tier: 'foundation' },
  { id: 'es-72', themeId: 'future', word: 'suspender', meaning: 'to fail (exam)', tier: 'higher' },
  { id: 'es-73', themeId: 'future', word: 'elegir', meaning: 'to choose', tier: 'foundation' },
  // Identity – Me, my family (continued)
  { id: 'es-74', themeId: 'identity', word: 'padrastro', meaning: 'stepfather', tier: 'foundation' },
  { id: 'es-75', themeId: 'identity', word: 'madrastra', meaning: 'stepmother', tier: 'foundation' },
  { id: 'es-76', themeId: 'identity', word: 'cuñado/cuñada', meaning: 'brother-in-law/sister-in-law', tier: 'higher' },
  { id: 'es-77', themeId: 'identity', word: 'novio/novia', meaning: 'boyfriend/girlfriend', tier: 'foundation' },
  { id: 'es-78', themeId: 'identity', word: 'personalidad', meaning: 'personality', tier: 'foundation' },
  { id: 'es-79', themeId: 'identity', word: 'carácter', meaning: 'character', tier: 'higher' },
  { id: 'es-80', themeId: 'identity', word: 'deportista', meaning: 'sporty', tier: 'foundation' },
  { id: 'es-81', themeId: 'identity', word: 'inteligente', meaning: 'intelligent', tier: 'foundation' },
  { id: 'es-82', themeId: 'identity', word: 'divertido', meaning: 'funny', tier: 'foundation' },
  // Identity – Technology (continued)
  { id: 'es-83', themeId: 'identity', word: 'móvil', meaning: 'mobile phone', tier: 'foundation' },
  { id: 'es-84', themeId: 'identity', word: 'mensaje', meaning: 'message', tier: 'foundation' },
  { id: 'es-85', themeId: 'identity', word: 'enviar', meaning: 'to send', tier: 'foundation' },
  { id: 'es-86', themeId: 'identity', word: 'recibir', meaning: 'to receive', tier: 'foundation' },
  { id: 'es-87', themeId: 'identity', word: 'búsqueda', meaning: 'search', tier: 'foundation' },
  { id: 'es-88', themeId: 'identity', word: 'página web', meaning: 'website', tier: 'foundation' },
  { id: 'es-89', themeId: 'identity', word: 'videojuego', meaning: 'video game', tier: 'foundation' },
  { id: 'es-90', themeId: 'identity', word: 'peligro', meaning: 'danger', tier: 'foundation' },
  { id: 'es-91', themeId: 'identity', word: 'ciberacoso', meaning: 'cyberbullying', tier: 'higher' },
  // Identity – Free time (continued)
  { id: 'es-92', themeId: 'identity', word: 'equipo', meaning: 'team', tier: 'foundation' },
  { id: 'es-93', themeId: 'identity', word: 'partido', meaning: 'match', tier: 'foundation' },
  { id: 'es-94', themeId: 'identity', word: 'ganar', meaning: 'to win', tier: 'foundation' },
  { id: 'es-95', themeId: 'identity', word: 'perder', meaning: 'to lose', tier: 'foundation' },
  { id: 'es-96', themeId: 'identity', word: 'correr', meaning: 'to run', tier: 'foundation' },
  { id: 'es-97', themeId: 'identity', word: 'montar en bici', meaning: 'to cycle', tier: 'foundation' },
  { id: 'es-98', themeId: 'identity', word: 'concierto', meaning: 'concert', tier: 'foundation' },
  { id: 'es-99', themeId: 'identity', word: 'película', meaning: 'film', tier: 'foundation' },
  { id: 'es-100', themeId: 'identity', word: 'serie', meaning: 'TV series', tier: 'foundation' },
  { id: 'es-101', themeId: 'identity', word: 'libro', meaning: 'book', tier: 'foundation' },
  { id: 'es-102', themeId: 'identity', word: 'revista', meaning: 'magazine', tier: 'foundation' },
  { id: 'es-103', themeId: 'identity', word: 'Navidad', meaning: 'Christmas', tier: 'foundation' },
  { id: 'es-104', themeId: 'identity', word: 'Semana Santa', meaning: 'Easter', tier: 'foundation' },
  { id: 'es-105', themeId: 'identity', word: 'cumpleaños', meaning: 'birthday', tier: 'foundation' },
  // Local/national/global (continued)
  { id: 'es-106', themeId: 'local-national-global', word: 'centro', meaning: 'town centre', tier: 'foundation' },
  { id: 'es-107', themeId: 'local-national-global', word: 'afueras', meaning: 'outskirts', tier: 'foundation' },
  { id: 'es-108', themeId: 'local-national-global', word: 'barrio', meaning: 'district/area', tier: 'foundation' },
  { id: 'es-109', themeId: 'local-national-global', word: 'edificio', meaning: 'building', tier: 'foundation' },
  { id: 'es-110', themeId: 'local-national-global', word: 'iglesia', meaning: 'church', tier: 'foundation' },
  { id: 'es-111', themeId: 'local-national-global', word: 'hospital', meaning: 'hospital', tier: 'foundation' },
  { id: 'es-112', themeId: 'local-national-global', word: 'ayuntamiento', meaning: 'town hall', tier: 'foundation' },
  { id: 'es-113', themeId: 'local-national-global', word: 'biblioteca', meaning: 'library', tier: 'foundation' },
  { id: 'es-114', themeId: 'local-national-global', word: 'piscina', meaning: 'swimming pool', tier: 'foundation' },
  { id: 'es-115', themeId: 'local-national-global', word: 'estadio', meaning: 'stadium', tier: 'foundation' },
  { id: 'es-116', themeId: 'local-national-global', word: 'restaurante', meaning: 'restaurant', tier: 'foundation' },
  { id: 'es-117', themeId: 'local-national-global', word: 'autobús', meaning: 'bus', tier: 'foundation' },
  { id: 'es-118', themeId: 'local-national-global', word: 'tren', meaning: 'train', tier: 'foundation' },
  { id: 'es-119', themeId: 'local-national-global', word: 'metro', meaning: 'metro', tier: 'foundation' },
  { id: 'es-120', themeId: 'local-national-global', word: 'coche', meaning: 'car', tier: 'foundation' },
  { id: 'es-121', themeId: 'local-national-global', word: 'bicicleta', meaning: 'bicycle', tier: 'foundation' },
  { id: 'es-122', themeId: 'local-national-global', word: 'a pie', meaning: 'on foot', tier: 'foundation' },
  { id: 'es-123', themeId: 'local-national-global', word: 'clima', meaning: 'climate', tier: 'foundation' },
  { id: 'es-124', themeId: 'local-national-global', word: 'reciclaje', meaning: 'recycling', tier: 'foundation' },
  { id: 'es-125', themeId: 'local-national-global', word: 'desarrollo sostenible', meaning: 'sustainable development', tier: 'higher' },
  { id: 'es-126', themeId: 'local-national-global', word: 'sin techo', meaning: 'homeless', tier: 'higher' },
  { id: 'es-127', themeId: 'local-national-global', word: 'voluntariado', meaning: 'volunteering', tier: 'higher' },
  { id: 'es-128', themeId: 'local-national-global', word: 'derechos humanos', meaning: 'human rights', tier: 'higher' },
  // Future (continued)
  { id: 'es-129', themeId: 'future', word: 'clase', meaning: 'class', tier: 'foundation' },
  { id: 'es-130', themeId: 'future', word: 'profesor', meaning: 'teacher', tier: 'foundation' },
  { id: 'es-131', themeId: 'future', word: 'alumno', meaning: 'pupil', tier: 'foundation' },
  { id: 'es-132', themeId: 'future', word: 'lección', meaning: 'lesson', tier: 'foundation' },
  { id: 'es-133', themeId: 'future', word: 'deberes', meaning: 'homework', tier: 'foundation' },
  { id: 'es-134', themeId: 'future', word: 'reglas', meaning: 'rules', tier: 'foundation' },
  { id: 'es-135', themeId: 'future', word: 'uniforme', meaning: 'uniform', tier: 'foundation' },
  { id: 'es-136', themeId: 'future', word: 'comedor', meaning: 'canteen', tier: 'foundation' },
  { id: 'es-137', themeId: 'future', word: 'tener éxito', meaning: 'to succeed', tier: 'foundation' },
  { id: 'es-138', themeId: 'future', word: 'aprobar', meaning: 'to pass (exam)', tier: 'foundation' },
  { id: 'es-139', themeId: 'future', word: 'obtener', meaning: 'to obtain/get', tier: 'foundation' },
  { id: 'es-140', themeId: 'future', word: 'título', meaning: 'qualification', tier: 'foundation' },
  { id: 'es-141', themeId: 'future', word: 'formación profesional', meaning: 'vocational training', tier: 'foundation' },
  { id: 'es-142', themeId: 'future', word: 'oficina', meaning: 'office', tier: 'foundation' },
  { id: 'es-143', themeId: 'future', word: 'jefe', meaning: 'boss', tier: 'foundation' },
  { id: 'es-144', themeId: 'future', word: 'compañero', meaning: 'colleague', tier: 'foundation' },
  // Time expressions and connectives
  { id: 'es-145', themeId: 'identity', word: 'ayer', meaning: 'yesterday', tier: 'foundation' },
  { id: 'es-146', themeId: 'identity', word: 'hoy', meaning: 'today', tier: 'foundation' },
  { id: 'es-147', themeId: 'identity', word: 'mañana', meaning: 'tomorrow', tier: 'foundation' },
  { id: 'es-148', themeId: 'identity', word: 'ahora', meaning: 'now', tier: 'foundation' },
  { id: 'es-149', themeId: 'identity', word: 'siempre', meaning: 'always', tier: 'foundation' },
  { id: 'es-150', themeId: 'identity', word: 'nunca', meaning: 'never', tier: 'foundation' },
  { id: 'es-151', themeId: 'identity', word: 'porque', meaning: 'because', tier: 'foundation' },
  { id: 'es-152', themeId: 'identity', word: 'por eso', meaning: 'so/therefore', tier: 'foundation' },
  { id: 'es-153', themeId: 'identity', word: 'pero', meaning: 'but', tier: 'foundation' },
  { id: 'es-154', themeId: 'identity', word: 'y', meaning: 'and', tier: 'foundation' },
  { id: 'es-155', themeId: 'identity', word: 'o', meaning: 'or', tier: 'foundation' },
  { id: 'es-156', themeId: 'identity', word: 'sin embargo', meaning: 'however', tier: 'higher' },
  { id: 'es-157', themeId: 'identity', word: 'no obstante', meaning: 'nevertheless', tier: 'higher' },
  { id: 'es-158', themeId: 'identity', word: 'además', meaning: 'moreover', tier: 'higher' },
  // Identity – Food, drink, daily life
  { id: 'es-159', themeId: 'identity', word: 'desayuno', meaning: 'breakfast', tier: 'foundation' },
  { id: 'es-160', themeId: 'identity', word: 'almuerzo', meaning: 'lunch', tier: 'foundation' },
  { id: 'es-161', themeId: 'identity', word: 'cena', meaning: 'dinner', tier: 'foundation' },
  { id: 'es-162', themeId: 'identity', word: 'pan', meaning: 'bread', tier: 'foundation' },
  { id: 'es-163', themeId: 'identity', word: 'agua', meaning: 'water', tier: 'foundation' },
  { id: 'es-164', themeId: 'identity', word: 'leche', meaning: 'milk', tier: 'foundation' },
  { id: 'es-165', themeId: 'identity', word: 'queso', meaning: 'cheese', tier: 'foundation' },
  { id: 'es-166', themeId: 'identity', word: 'carne', meaning: 'meat', tier: 'foundation' },
  { id: 'es-167', themeId: 'identity', word: 'pescado', meaning: 'fish', tier: 'foundation' },
  { id: 'es-168', themeId: 'identity', word: 'verduras', meaning: 'vegetables', tier: 'foundation' },
  { id: 'es-169', themeId: 'identity', word: 'fruta', meaning: 'fruit', tier: 'foundation' },
  { id: 'es-170', themeId: 'identity', word: 'manzana', meaning: 'apple', tier: 'foundation' },
  { id: 'es-171', themeId: 'identity', word: 'chocolate', meaning: 'chocolate', tier: 'foundation' },
  { id: 'es-172', themeId: 'identity', word: 'helado', meaning: 'ice cream', tier: 'foundation' },
  { id: 'es-173', themeId: 'identity', word: 'beber', meaning: 'to drink', tier: 'foundation' },
  { id: 'es-174', themeId: 'identity', word: 'comer', meaning: 'to eat', tier: 'foundation' },
  { id: 'es-175', themeId: 'identity', word: 'preferir', meaning: 'to prefer', tier: 'foundation' },
  { id: 'es-176', themeId: 'identity', word: 'gustar', meaning: 'to like', tier: 'foundation' },
  { id: 'es-177', themeId: 'identity', word: 'odiar', meaning: 'to hate', tier: 'foundation' },
  { id: 'es-178', themeId: 'identity', word: 'encantar', meaning: 'to love', tier: 'foundation' },
  // Identity – Weather, clothes, body
  { id: 'es-179', themeId: 'identity', word: 'hace buen tiempo', meaning: 'the weather is nice', tier: 'foundation' },
  { id: 'es-180', themeId: 'identity', word: 'llueve', meaning: 'it is raining', tier: 'foundation' },
  { id: 'es-181', themeId: 'identity', word: 'nieva', meaning: 'it is snowing', tier: 'foundation' },
  { id: 'es-182', themeId: 'identity', word: 'caliente', meaning: 'hot', tier: 'foundation' },
  { id: 'es-183', themeId: 'identity', word: 'frío', meaning: 'cold', tier: 'foundation' },
  { id: 'es-184', themeId: 'identity', word: 'ropa', meaning: 'clothes', tier: 'foundation' },
  { id: 'es-185', themeId: 'identity', word: 'camisa', meaning: 'shirt', tier: 'foundation' },
  { id: 'es-186', themeId: 'identity', word: 'pantalones', meaning: 'trousers', tier: 'foundation' },
  { id: 'es-187', themeId: 'identity', word: 'vestido', meaning: 'dress', tier: 'foundation' },
  { id: 'es-188', themeId: 'identity', word: 'zapatos', meaning: 'shoes', tier: 'foundation' },
  { id: 'es-189', themeId: 'identity', word: 'llevar', meaning: 'to wear', tier: 'foundation' },
  { id: 'es-190', themeId: 'identity', word: 'cuerpo', meaning: 'body', tier: 'foundation' },
  { id: 'es-191', themeId: 'identity', word: 'cabeza', meaning: 'head', tier: 'foundation' },
  { id: 'es-192', themeId: 'identity', word: 'ojos', meaning: 'eyes', tier: 'foundation' },
  { id: 'es-193', themeId: 'identity', word: 'salud', meaning: 'health', tier: 'foundation' },
  { id: 'es-194', themeId: 'identity', word: 'enfermo', meaning: 'ill', tier: 'foundation' },
  { id: 'es-195', themeId: 'identity', word: 'cansado', meaning: 'tired', tier: 'foundation' },
  { id: 'es-196', themeId: 'identity', word: 'contento', meaning: 'happy', tier: 'foundation' },
  { id: 'es-197', themeId: 'identity', word: 'triste', meaning: 'sad', tier: 'foundation' },
  { id: 'es-198', themeId: 'identity', word: 'enfadado', meaning: 'angry', tier: 'foundation' },
  // Local/national/global – Travel, directions, opinions
  { id: 'es-199', themeId: 'local-national-global', word: 'hotel', meaning: 'hotel', tier: 'foundation' },
  { id: 'es-200', themeId: 'local-national-global', word: 'avión', meaning: 'plane', tier: 'foundation' },
  { id: 'es-201', themeId: 'local-national-global', word: 'barco', meaning: 'boat', tier: 'foundation' },
  { id: 'es-202', themeId: 'local-national-global', word: 'billete', meaning: 'ticket', tier: 'foundation' },
  { id: 'es-203', themeId: 'local-national-global', word: 'pasaporte', meaning: 'passport', tier: 'foundation' },
  { id: 'es-204', themeId: 'local-national-global', word: 'derecha', meaning: 'right', tier: 'foundation' },
  { id: 'es-205', themeId: 'local-national-global', word: 'izquierda', meaning: 'left', tier: 'foundation' },
  { id: 'es-206', themeId: 'local-national-global', word: 'todo recto', meaning: 'straight ahead', tier: 'foundation' },
  { id: 'es-207', themeId: 'local-national-global', word: 'cerca de', meaning: 'near', tier: 'foundation' },
  { id: 'es-208', themeId: 'local-national-global', word: 'lejos de', meaning: 'far from', tier: 'foundation' },
  { id: 'es-209', themeId: 'local-national-global', word: 'mundo', meaning: 'world', tier: 'foundation' },
  { id: 'es-210', themeId: 'local-national-global', word: 'extranjero', meaning: 'foreign/abroad', tier: 'foundation' },
  { id: 'es-211', themeId: 'local-national-global', word: 'idioma', meaning: 'language', tier: 'foundation' },
  { id: 'es-212', themeId: 'local-national-global', word: 'español', meaning: 'Spanish', tier: 'foundation' },
  { id: 'es-213', themeId: 'local-national-global', word: 'inglés', meaning: 'English', tier: 'foundation' },
  // Future – School, work (continued)
  { id: 'es-214', themeId: 'future', word: 'aula', meaning: 'classroom', tier: 'foundation' },
  { id: 'es-215', themeId: 'future', word: 'repasar', meaning: 'to revise', tier: 'foundation' },
  { id: 'es-216', themeId: 'future', word: 'hacer un examen', meaning: 'to take an exam', tier: 'foundation' },
  { id: 'es-217', themeId: 'future', word: 'bachillerato', meaning: 'A-levels/sixth form', tier: 'foundation' },
  { id: 'es-218', themeId: 'future', word: 'formación', meaning: 'training', tier: 'foundation' },
  { id: 'es-219', themeId: 'future', word: 'médico', meaning: 'doctor', tier: 'foundation' },
  { id: 'es-220', themeId: 'future', word: 'enfermero', meaning: 'nurse', tier: 'foundation' },
  { id: 'es-221', themeId: 'future', word: 'abogado', meaning: 'lawyer', tier: 'foundation' },
  { id: 'es-222', themeId: 'future', word: 'ingeniero', meaning: 'engineer', tier: 'foundation' },
  { id: 'es-223', themeId: 'future', word: 'dependiente', meaning: 'shop assistant', tier: 'foundation' },
  { id: 'es-224', themeId: 'future', word: 'trabajar', meaning: 'to work', tier: 'foundation' },
  { id: 'es-225', themeId: 'future', word: 'ganarse la vida', meaning: 'to earn a living', tier: 'higher' },
  { id: 'es-226', themeId: 'future', word: 'ambición', meaning: 'ambition', tier: 'foundation' },
  { id: 'es-227', themeId: 'future', word: 'sueño', meaning: 'dream', tier: 'foundation' },
  { id: 'es-228', themeId: 'future', word: 'desear', meaning: 'to wish', tier: 'foundation' },
  // Opinions and reasons
  { id: 'es-229', themeId: 'identity', word: 'creo que', meaning: 'I think that', tier: 'foundation' },
  { id: 'es-230', themeId: 'identity', word: 'en mi opinión', meaning: 'in my opinion', tier: 'foundation' },
  { id: 'es-231', themeId: 'identity', word: 'pienso que', meaning: 'I believe that', tier: 'foundation' },
  { id: 'es-232', themeId: 'identity', word: 'es', meaning: 'it is', tier: 'foundation' },
  { id: 'es-233', themeId: 'identity', word: 'hay', meaning: 'there is/are', tier: 'foundation' },
  { id: 'es-234', themeId: 'identity', word: 'mucho', meaning: 'a lot', tier: 'foundation' },
  { id: 'es-235', themeId: 'identity', word: 'poco', meaning: 'little/few', tier: 'foundation' },
  { id: 'es-236', themeId: 'identity', word: 'bastante', meaning: 'enough', tier: 'foundation' },
  { id: 'es-237', themeId: 'identity', word: 'demasiado', meaning: 'too much', tier: 'foundation' },
  { id: 'es-238', themeId: 'identity', word: 'muy', meaning: 'very', tier: 'foundation' },
  { id: 'es-239', themeId: 'identity', word: 'más', meaning: 'more', tier: 'foundation' },
  { id: 'es-240', themeId: 'identity', word: 'menos', meaning: 'less', tier: 'foundation' },
  { id: 'es-241', themeId: 'identity', word: 'bien', meaning: 'well', tier: 'foundation' },
  { id: 'es-242', themeId: 'identity', word: 'mal', meaning: 'badly', tier: 'foundation' },
  { id: 'es-243', themeId: 'identity', word: 'realmente', meaning: 'really', tier: 'foundation' },
  // Numbers and quantities
  { id: 'es-244', themeId: 'identity', word: 'primero', meaning: 'first', tier: 'foundation' },
  { id: 'es-245', themeId: 'identity', word: 'último', meaning: 'last', tier: 'foundation' },
  { id: 'es-246', themeId: 'identity', word: 'cada', meaning: 'each', tier: 'foundation' },
  { id: 'es-247', themeId: 'identity', word: 'alguno', meaning: 'some', tier: 'foundation' },
  { id: 'es-248', themeId: 'identity', word: 'todo', meaning: 'all', tier: 'foundation' },
  { id: 'es-249', themeId: 'identity', word: 'nada', meaning: 'nothing', tier: 'foundation' },
  { id: 'es-250', themeId: 'identity', word: 'algo', meaning: 'something', tier: 'foundation' },
  { id: 'es-251', themeId: 'identity', word: 'nadie', meaning: 'nobody', tier: 'foundation' },
  { id: 'es-252', themeId: 'identity', word: 'dónde', meaning: 'where', tier: 'foundation' },
  { id: 'es-253', themeId: 'identity', word: 'cuándo', meaning: 'when', tier: 'foundation' },
  { id: 'es-254', themeId: 'identity', word: 'cómo', meaning: 'how', tier: 'foundation' },
  { id: 'es-255', themeId: 'identity', word: 'por qué', meaning: 'why', tier: 'foundation' },
  { id: 'es-256', themeId: 'identity', word: 'cuánto', meaning: 'how much/many', tier: 'foundation' },
  { id: 'es-257', themeId: 'identity', word: 'cuál', meaning: 'which', tier: 'foundation' },
  { id: 'es-258', themeId: 'identity', word: 'quién', meaning: 'who', tier: 'foundation' },
  // Higher tier – extended
  { id: 'es-259', themeId: 'identity', word: 'evidentemente', meaning: 'obviously', tier: 'higher' },
  { id: 'es-260', themeId: 'identity', word: 'desafortunadamente', meaning: 'unfortunately', tier: 'higher' },
  { id: 'es-261', themeId: 'local-national-global', word: 'calentamiento global', meaning: 'global warming', tier: 'higher' },
  { id: 'es-262', themeId: 'local-national-global', word: 'desigualdad', meaning: 'inequality', tier: 'higher' },
  { id: 'es-263', themeId: 'future', word: 'paro', meaning: 'unemployment', tier: 'higher' },
  { id: 'es-264', themeId: 'future', word: 'competencia', meaning: 'competition', tier: 'higher' },
  // Implementation plan expansion — toward 1,200+ Foundation
  { id: 'es-265', themeId: 'identity', word: 'saber', meaning: 'to know (fact)', tier: 'foundation' },
  { id: 'es-266', themeId: 'identity', word: 'conocer', meaning: 'to know (person/place)', tier: 'foundation' },
  { id: 'es-267', themeId: 'identity', word: 'poder', meaning: 'to be able to', tier: 'foundation' },
  { id: 'es-268', themeId: 'identity', word: 'querer', meaning: 'to want', tier: 'foundation' },
  { id: 'es-269', themeId: 'identity', word: 'deber', meaning: 'to have to/must', tier: 'foundation' },
  { id: 'es-270', themeId: 'identity', word: 'venir', meaning: 'to come', tier: 'foundation' },
  { id: 'es-271', themeId: 'identity', word: 'salir', meaning: 'to leave', tier: 'foundation' },
  { id: 'es-272', themeId: 'identity', word: 'llegar', meaning: 'to arrive', tier: 'foundation' },
  { id: 'es-273', themeId: 'identity', word: 'quedarse', meaning: 'to stay', tier: 'foundation' },
  { id: 'es-274', themeId: 'identity', word: 'ir', meaning: 'to go', tier: 'foundation' },
  { id: 'es-275', themeId: 'identity', word: 'hacer', meaning: 'to do/make', tier: 'foundation' },
  { id: 'es-276', themeId: 'identity', word: 'tomar', meaning: 'to take', tier: 'foundation' },
  { id: 'es-277', themeId: 'identity', word: 'ver', meaning: 'to see', tier: 'foundation' },
  { id: 'es-278', themeId: 'identity', word: 'creer', meaning: 'to believe', tier: 'foundation' },
  { id: 'es-279', themeId: 'local-national-global', word: 'cambio climático', meaning: 'climate change', tier: 'higher' },
  { id: 'es-280', themeId: 'local-national-global', word: 'biodiversidad', meaning: 'biodiversity', tier: 'higher' },
  { id: 'es-281', themeId: 'local-national-global', word: 'deforestación', meaning: 'deforestation', tier: 'higher' },
  { id: 'es-282', themeId: 'future', word: 'habilidad', meaning: 'skill', tier: 'foundation' },
  { id: 'es-283', themeId: 'future', word: 'experiencia', meaning: 'experience', tier: 'foundation' },
  { id: 'es-284', themeId: 'future', word: 'entrevista', meaning: 'interview', tier: 'foundation' },
  { id: 'es-285', themeId: 'future', word: 'currículum', meaning: 'CV', tier: 'foundation' },
  { id: 'es-286', themeId: 'identity', word: 'solo', meaning: 'only', tier: 'foundation' },
  { id: 'es-287', themeId: 'identity', word: 'todavía', meaning: 'still/yet', tier: 'foundation' },
  { id: 'es-288', themeId: 'identity', word: 'ya', meaning: 'already', tier: 'foundation' },
  { id: 'es-289', themeId: 'identity', word: 'pronto', meaning: 'soon', tier: 'foundation' },
  { id: 'es-290', themeId: 'identity', word: 'tarde', meaning: 'late', tier: 'foundation' },
  { id: 'es-291', themeId: 'identity', word: 'temprano', meaning: 'early', tier: 'foundation' },
  { id: 'es-292', themeId: 'identity', word: 'aquí', meaning: 'here', tier: 'foundation' },
  { id: 'es-293', themeId: 'identity', word: 'allí', meaning: 'there', tier: 'foundation' },
  { id: 'es-294', themeId: 'identity', word: 'en todas partes', meaning: 'everywhere', tier: 'foundation' },
  { id: 'es-295', themeId: 'local-national-global', word: 'frontera', meaning: 'border', tier: 'foundation' },
  { id: 'es-296', themeId: 'local-national-global', word: 'continente', meaning: 'continent', tier: 'foundation' },
  { id: 'es-297', themeId: 'local-national-global', word: 'océano', meaning: 'ocean', tier: 'foundation' },
  { id: 'es-298', themeId: 'local-national-global', word: 'mar', meaning: 'sea', tier: 'foundation' },
  { id: 'es-299', themeId: 'local-national-global', word: 'río', meaning: 'river', tier: 'foundation' },
  { id: 'es-300', themeId: 'local-national-global', word: 'lago', meaning: 'lake', tier: 'foundation' },
  { id: 'es-301', themeId: 'local-national-global', word: 'bosque', meaning: 'forest', tier: 'foundation' },
  { id: 'es-302', themeId: 'local-national-global', word: 'isla', meaning: 'island', tier: 'foundation' },
  { id: 'es-303', themeId: 'local-national-global', word: 'desierto', meaning: 'desert', tier: 'foundation' },
  { id: 'es-304', themeId: 'future', word: 'salario mínimo', meaning: 'minimum wage', tier: 'higher' },
  { id: 'es-305', themeId: 'future', word: 'contrato', meaning: 'contract', tier: 'foundation' },
  { id: 'es-306', themeId: 'future', word: 'vacaciones', meaning: 'holiday/leave', tier: 'foundation' },
  { id: 'es-307', themeId: 'future', word: 'jubilación', meaning: 'retirement', tier: 'foundation' },
  { id: 'es-308', themeId: 'identity', word: 'salud mental', meaning: 'mental health', tier: 'higher' },
  { id: 'es-309', themeId: 'identity', word: 'bienestar', meaning: 'wellbeing', tier: 'higher' },
];

/** Get vocab for a language, optionally filtered by theme and tier */
export function getMflVocab(lang: LanguageId, themeId?: ThemeId, tier?: 'foundation' | 'higher'): MflVocabItem[] {
  const list = lang === 'french' ? VOCAB_FRENCH : VOCAB_SPANISH;
  let out = list;
  if (themeId) out = out.filter(v => v.themeId === themeId);
  if (tier) out = out.filter(v => v.tier === tier || v.tier === 'foundation');
  return out;
}
