/**
 * MFL Grammar Lab – French & Spanish (AQA 8658/8698)
 */
import type { MflGrammarConcept } from '../types/mflLab';
import type { LanguageId } from './languagesHubData';

const FRENCH_GRAMMAR: MflGrammarConcept[] = [
  {
    id: 'fr-g1',
    title: 'Present tense (-er verbs)',
    tense: 'présent',
    coreIdea: 'Regular -er verbs: remove -er, add -e, -es, -e, -ons, -ez, -ent',
    conjugation: [
      { pronoun: 'je', form: '-e' },
      { pronoun: 'tu', form: '-es' },
      { pronoun: 'il/elle', form: '-e' },
      { pronoun: 'nous', form: '-ons' },
      { pronoun: 'vous', form: '-ez' },
      { pronoun: 'ils/elles', form: '-ent' },
    ],
    examples: ['Je parle français.', 'Tu manges une pomme.', 'Il écoute de la musique.'],
    commonMistake: 'Many students write "je parl" instead of "je parle"',
    correctForm: 'The -er ending is always replaced; the final consonant is kept for nous/vous.',
  },
  {
    id: 'fr-g2',
    title: 'Passé composé (perfect tense)',
    tense: 'passé composé',
    coreIdea: 'avoir/être + past participle. Most verbs use avoir.',
    conjugation: [
      { pronoun: 'j\'', form: 'ai + pp' },
      { pronoun: 'tu', form: 'as + pp' },
      { pronoun: 'il/elle', form: 'a + pp' },
      { pronoun: 'nous', form: 'avons + pp' },
      { pronoun: 'vous', form: 'avez + pp' },
      { pronoun: 'ils/elles', form: 'ont + pp' },
    ],
    examples: ['J\'ai mangé une pizza.', 'Elle a voyagé en France.', 'Nous avons parlé.'],
    commonMistake: 'Many students forget the past participle agreement with être (elle est allée)',
    correctForm: 'With être, the past participle agrees with the subject in gender and number.',
  },
  {
    id: 'fr-g3',
    title: 'Imperfect tense',
    tense: 'imparfait',
    coreIdea: 'Stem (nous form minus -ons) + -ais, -ais, -ait, -ions, -iez, -aient',
    conjugation: [
      { pronoun: 'je', form: '-ais' },
      { pronoun: 'tu', form: '-ais' },
      { pronoun: 'il/elle', form: '-ait' },
      { pronoun: 'nous', form: '-ions' },
      { pronoun: 'vous', form: '-iez' },
      { pronoun: 'ils/elles', form: '-aient' },
    ],
    examples: ['Quand j\'étais jeune, je jouais au football.', 'Il faisait beau.'],
    commonMistake: 'Confusing imperfect with passé composé – imperfect = ongoing/habitual',
    correctForm: 'Imperfect = background, habit, description. Passé composé = completed action.',
  },
  {
    id: 'fr-g4',
    title: 'Future tense',
    tense: 'futur simple',
    coreIdea: 'Infinitive + -ai, -as, -a, -ons, -ez, -ont (regular -er/-ir)',
    conjugation: [
      { pronoun: 'je', form: '-ai' },
      { pronoun: 'tu', form: '-as' },
      { pronoun: 'il/elle', form: '-a' },
      { pronoun: 'nous', form: '-ons' },
      { pronoun: 'vous', form: '-ez' },
      { pronoun: 'ils/elles', form: '-ont' },
    ],
    examples: ['Je voyagerai en France.', 'Tu mangeras demain.'],
    commonMistake: 'Writing "je vais voyager" (near future) when exam asks for simple future',
    correctForm: 'Futur simple = will + verb. Near future = aller + infinitive.',
  },
  {
    id: 'fr-g5',
    title: 'Negation (ne...pas)',
    tense: undefined,
    coreIdea: 'Ne + verb + pas. Ne becomes n\' before a vowel.',
    examples: ['Je ne mange pas de viande.', 'Il n\'a pas de frère.'],
    commonMistake: 'Forgetting "ne" – many students write only "pas"',
    correctForm: 'Both "ne" and "pas" are required in formal written French.',
  },
  {
    id: 'fr-g6',
    title: 'Adjective agreement',
    tense: undefined,
    coreIdea: 'Adjectives agree in gender (m/f) and number (s/pl) with the noun.',
    examples: ['Une grande maison.', 'Des amis intelligents.', 'Une fille sportive.'],
    commonMistake: 'Adding -e to adjectives that already end in -e (e.g. jeune)',
    correctForm: 'Adjectives ending in -e (jeune, facile) don\'t change for feminine.',
  },
  {
    id: 'fr-g7',
    title: 'Question formation',
    tense: undefined,
    coreIdea: 'Intonation, est-ce que, or inversion (verb + subject).',
    examples: ['Tu parles français?', 'Est-ce que tu parles français?', 'Parles-tu français?'],
    commonMistake: 'Inversion: forgetting the hyphen (Parles-tu)',
    correctForm: 'Inversion requires a hyphen: verb-tu, verb-il, etc.',
  },
  {
    id: 'fr-g8',
    title: 'Direct object pronouns',
    tense: undefined,
    coreIdea: 'me, te, le/la/l\', nous, vous, les – go before the verb (except affirmative imperative).',
    examples: ['Je le vois.', 'Elle la mange.', 'Nous les aimons.'],
    commonMistake: 'Putting the pronoun after the verb in simple tenses',
    correctForm: 'In present/imperfect/future: pronoun before verb. Je le mange.',
  },
  {
    id: 'fr-g9',
    title: 'Conditional tense',
    tense: 'conditionnel',
    coreIdea: 'Infinitive + -ais, -ais, -ait, -ions, -iez, -aient (same endings as imperfect)',
    conjugation: [
      { pronoun: 'je', form: '-ais' },
      { pronoun: 'tu', form: '-ais' },
      { pronoun: 'il/elle', form: '-ait' },
      { pronoun: 'nous', form: '-ions' },
      { pronoun: 'vous', form: '-iez' },
      { pronoun: 'ils/elles', form: '-aient' },
    ],
    examples: ['Je voudrais un café.', 'Il voyagerait en Espagne.'],
    commonMistake: 'Confusing conditional with future – conditional = would + verb',
    correctForm: 'Conditional = would/could. Future = will.',
  },
  {
    id: 'fr-g10',
    title: 'Reflexive verbs',
    tense: undefined,
    coreIdea: 'se + verb. Reflexive pronoun agrees with subject: me, te, se, nous, vous, se.',
    examples: ['Je me lève à sept heures.', 'Elle s\'habille.', 'Nous nous amusons.'],
    commonMistake: 'Using "se" for "nous" – it should be "nous" (nous nous levons)',
    correctForm: 'Nous and vous use the same form twice: nous nous, vous vous.',
  },
  {
    id: 'fr-g11',
    title: 'Present tense (-ir verbs)',
    tense: 'présent',
    coreIdea: 'Remove -ir, add -is, -is, -it, -issons, -issez, -issent',
    conjugation: [
      { pronoun: 'je', form: '-is' },
      { pronoun: 'tu', form: '-is' },
      { pronoun: 'il/elle', form: '-it' },
      { pronoun: 'nous', form: '-issons' },
      { pronoun: 'vous', form: '-issez' },
      { pronoun: 'ils/elles', form: '-issent' },
    ],
    examples: ['Je finis mes devoirs.', 'Nous choisissons le film.'],
    commonMistake: 'Confusing -ir with -er endings',
    correctForm: '-ir verbs have -iss- in nous/vous forms.',
  },
  {
    id: 'fr-g12',
    title: 'Present tense (-re verbs)',
    tense: 'présent',
    coreIdea: 'Remove -re, add -s, -s, - (nothing), -ons, -ez, -ent',
    conjugation: [
      { pronoun: 'je', form: '-s' },
      { pronoun: 'tu', form: '-s' },
      { pronoun: 'il/elle', form: '-' },
      { pronoun: 'nous', form: '-ons' },
      { pronoun: 'vous', form: '-ez' },
      { pronoun: 'ils/elles', form: '-ent' },
    ],
    examples: ['Je vends ma voiture.', 'Il attend le bus.'],
    commonMistake: 'Adding -s to il/elle form (il vend not il vends)',
    correctForm: 'Third person singular has no ending for regular -re.',
  },
  {
    id: 'fr-g13',
    title: 'Comparatives and superlatives',
    tense: undefined,
    coreIdea: 'Plus...que (more than), moins...que (less than), aussi...que (as...as). Le/la/les plus (superlative).',
    examples: ['Il est plus grand que moi.', 'C\'est le plus beau film.', 'Elle est aussi intelligente que son frère.'],
    commonMistake: 'Using "plus bon" instead of "meilleur"',
    correctForm: 'Bon → meilleur (better), mauvais → pire (worse).',
  },
  {
    id: 'fr-g14',
    title: 'Indirect object pronouns',
    tense: undefined,
    coreIdea: 'lui, leur – go before the verb. Lui = to him/her, leur = to them.',
    examples: ['Je lui donne le livre.', 'Nous leur parlons.'],
    commonMistake: 'Using "lui" for things – lui/leur are for people only',
    correctForm: 'For things: y (there) or le/la/les (direct object).',
  },
  {
    id: 'fr-g15',
    title: 'Y and en',
    tense: undefined,
    coreIdea: 'Y = there, to it (replaces à + place/thing). En = some, of it/them (replaces de + noun).',
    examples: ['J\'y vais.', 'J\'en ai trois.', 'Tu en veux?'],
    commonMistake: 'Putting y/en after the verb in compound tenses – they go before avoir/être',
    correctForm: 'J\'y suis allé. Nous en avons mangé.',
  },
  {
    id: 'fr-g16',
    title: 'Si + present → future',
    tense: undefined,
    coreIdea: 'Si + present in the "if" clause, future (or present) in the main clause.',
    examples: ['S\'il pleut, je resterai à la maison.', 'Si tu viens, on ira au cinéma.'],
    commonMistake: 'Using future in the si clause – never "s\'il pleuvra"',
    correctForm: 'Si is always followed by present (or imperfect for hypothetical).',
  },
  {
    id: 'fr-g17',
    title: 'Pluperfect (plus-que-parfait)',
    tense: 'plus-que-parfait',
    coreIdea: 'Imperfect of avoir/être + past participle. For an action before another past action.',
    conjugation: [
      { pronoun: 'j\'', form: 'avais + pp' },
      { pronoun: 'tu', form: 'avais + pp' },
      { pronoun: 'il/elle', form: 'avait + pp' },
      { pronoun: 'nous', form: 'avions + pp' },
      { pronoun: 'vous', form: 'aviez + pp' },
      { pronoun: 'ils/elles', form: 'avaient + pp' },
    ],
    examples: ['J\'avais mangé quand il est arrivé.', 'Elle était partie avant le dîner.'],
    commonMistake: 'Using pluperfect for a single past action',
    correctForm: 'Pluperfect = had done, before another past event.',
  },
  {
    id: 'fr-g18',
    title: 'Relative pronouns qui, que, où',
    tense: undefined,
    coreIdea: 'Qui = who/which (subject). Que = whom/which (object). Où = where/when.',
    examples: ['L\'homme qui parle est mon professeur.', 'Le livre que je lis est intéressant.', 'La ville où j\'habite.'],
    commonMistake: 'Using "que" when the pronoun is the subject',
    correctForm: 'Qui = subject of the verb that follows. Que = object.',
  },
  {
    id: 'fr-g19',
    title: 'Depuis, pendant, pour',
    tense: undefined,
    coreIdea: 'Depuis = since/for (ongoing). Pendant = for (completed). Pour = for (future duration).',
    examples: ['J\'habite ici depuis cinq ans.', 'J\'ai travaillé pendant deux heures.', 'Je pars pour une semaine.'],
    commonMistake: 'Using "depuis" with passé composé for a finished period',
    correctForm: 'Depuis + present = started in past, still true. Pendant + passé composé = completed.',
  },
  {
    id: 'fr-g20',
    title: 'Venir de + infinitive',
    tense: undefined,
    coreIdea: 'Venir de + infinitive = to have just done something.',
    examples: ['Je viens de manger.', 'Il vient d\'arriver.'],
    commonMistake: 'Using "je viens manger" (I come to eat) instead of "je viens de manger" (I have just eaten)',
    correctForm: '"De" is essential: venir de + infinitive = just did.',
  },
];

const SPANISH_GRAMMAR: MflGrammarConcept[] = [
  {
    id: 'es-g1',
    title: 'Present tense (-ar verbs)',
    tense: 'presente',
    coreIdea: 'Remove -ar, add -o, -as, -a, -amos, -áis, -an',
    conjugation: [
      { pronoun: 'yo', form: '-o' },
      { pronoun: 'tú', form: '-as' },
      { pronoun: 'él/ella', form: '-a' },
      { pronoun: 'nosotros', form: '-amos' },
      { pronoun: 'vosotros', form: '-áis' },
      { pronoun: 'ellos/ellas', form: '-an' },
    ],
    examples: ['Yo hablo español.', 'Ella estudia mucho.', 'Nosotros viajamos.'],
    commonMistake: 'Confusing -ar with -er/-ir endings',
    correctForm: '-ar has -a in él/ella; -er/-ir have -e.',
  },
  {
    id: 'es-g2',
    title: 'Preterite tense',
    tense: 'pretérito',
    coreIdea: 'Completed actions in the past. Regular -ar: -é, -aste, -ó, -amos, -asteis, -aron',
    conjugation: [
      { pronoun: 'yo', form: '-é' },
      { pronoun: 'tú', form: '-aste' },
      { pronoun: 'él/ella', form: '-ó' },
      { pronoun: 'nosotros', form: '-amos' },
      { pronoun: 'vosotros', form: '-asteis' },
      { pronoun: 'ellos/ellas', form: '-aron' },
    ],
    examples: ['Ayer comí pizza.', 'Ella viajó a Madrid.'],
    commonMistake: 'Using preterite for ongoing/habitual past (use imperfect instead)',
    correctForm: 'Preterite = one-off, completed. Imperfect = ongoing, habitual.',
  },
  {
    id: 'es-g3',
    title: 'Imperfect tense',
    tense: 'imperfecto',
    coreIdea: 'Ongoing or habitual past. -ar: -aba, -abas, -aba, -ábamos, -abais, -aban',
    conjugation: [
      { pronoun: 'yo', form: '-aba' },
      { pronoun: 'tú', form: '-abas' },
      { pronoun: 'él/ella', form: '-aba' },
      { pronoun: 'nosotros', form: '-ábamos' },
      { pronoun: 'vosotros', form: '-abais' },
      { pronoun: 'ellos/ellas', form: '-aban' },
    ],
    examples: ['Cuando era pequeño, jugaba al fútbol.', 'Siempre comía en casa.'],
    commonMistake: 'Using imperfect for a single completed action',
    correctForm: 'Imperfect = background, habit. Preterite = completed event.',
  },
  {
    id: 'es-g4',
    title: 'Future tense',
    tense: 'futuro',
    coreIdea: 'Infinitive + -é, -ás, -á, -emos, -éis, -án',
    conjugation: [
      { pronoun: 'yo', form: '-é' },
      { pronoun: 'tú', form: '-ás' },
      { pronoun: 'él/ella', form: '-á' },
      { pronoun: 'nosotros', form: '-emos' },
      { pronoun: 'vosotros', form: '-éis' },
      { pronoun: 'ellos/ellas', form: '-án' },
    ],
    examples: ['Mañana viajaré a Barcelona.', 'Ella estudiará medicina.'],
    commonMistake: 'Confusing future with "ir a + infinitive" (voy a viajar)',
    correctForm: 'Future = will. Ir a + infinitive = going to.',
  },
  {
    id: 'es-g5',
    title: 'Ser vs Estar',
    tense: undefined,
    coreIdea: 'Ser = permanent (identity, origin). Estar = temporary (location, condition).',
    examples: ['Soy español. (identity)', 'Estoy cansado. (condition)', 'Estoy en Madrid. (location)'],
    commonMistake: 'Using "ser" for location – location always uses "estar"',
    correctForm: 'Estar for location (estoy en casa), emotions (estoy feliz), temporary states.',
  },
  {
    id: 'es-g6',
    title: 'Gustar and similar verbs',
    tense: undefined,
    coreIdea: 'Gustar = "to please". Subject is the thing liked; indirect object is the person.',
    examples: ['Me gusta el fútbol.', 'Me gustan las películas.', 'Le gusta viajar.'],
    commonMistake: 'Saying "Yo gusto" – the person is the indirect object (me/te/le)',
    correctForm: 'Me gusta(n) = it/they please me. Use gusta for singular, gustan for plural.',
  },
  {
    id: 'es-g7',
    title: 'Por vs Para',
    tense: undefined,
    coreIdea: 'Por = through, for (reason), by. Para = for (purpose), towards, by (deadline).',
    examples: ['Gracias por la ayuda.', 'Estudio para el examen.', 'Para las ocho.'],
    commonMistake: 'Using "para" for "thanks for" – it\'s "gracias por"',
    correctForm: 'Gracias por, por favor, por eso, por la mañana. Para = purpose/destination.',
  },
  {
    id: 'es-g8',
    title: 'Direct object pronouns',
    tense: undefined,
    coreIdea: 'me, te, lo/la, nos, os, los/las – before conjugated verb or attached to infinitive.',
    examples: ['Lo veo.', 'La como.', 'Quiero verla.'],
    commonMistake: 'Using "le" for masculine direct object – "le" is indirect',
    correctForm: 'Lo/la for direct object. Le/les for indirect object (to/for someone).',
  },
  {
    id: 'es-g9',
    title: 'Adjective agreement',
    tense: undefined,
    coreIdea: 'Adjectives agree in gender (-o/-a) and number (-s) with the noun.',
    examples: ['Una casa grande.', 'Unos amigos simpáticos.', 'Las chicas inteligentes.'],
    commonMistake: 'Forgetting -s for plural (los libros rojo → los libros rojos)',
    correctForm: 'Add -s for plural. Change -o to -a for feminine (unless ends in -e).',
  },
  {
    id: 'es-g10',
    title: 'Reflexive verbs',
    tense: undefined,
    coreIdea: 'me, te, se, nos, os, se – before verb or attached to infinitive/gerund.',
    examples: ['Me levanto a las siete.', 'Ella se lava.', 'Vamos a vestirnos.'],
    commonMistake: 'Using "se" for "nosotros" – it\'s "nos" (nos levantamos)',
    correctForm: 'Nosotros = nos. Ellos = se. Position: before verb or attached to infinitive.',
  },
  {
    id: 'es-g11',
    title: 'Present tense (-er verbs)',
    tense: 'presente',
    coreIdea: 'Remove -er, add -o, -es, -e, -emos, -éis, -en',
    conjugation: [
      { pronoun: 'yo', form: '-o' },
      { pronoun: 'tú', form: '-es' },
      { pronoun: 'él/ella', form: '-e' },
      { pronoun: 'nosotros', form: '-emos' },
      { pronoun: 'vosotros', form: '-éis' },
      { pronoun: 'ellos/ellas', form: '-en' },
    ],
    examples: ['Yo como una manzana.', 'Ella bebe agua.'],
    commonMistake: 'Confusing -er with -ir (comer vs vivir)',
    correctForm: '-er has -e in él/ella; -ir has -e but different nosotros (-imos).',
  },
  {
    id: 'es-g12',
    title: 'Present tense (-ir verbs)',
    tense: 'presente',
    coreIdea: 'Remove -ir, add -o, -es, -e, -imos, -ís, -en',
    conjugation: [
      { pronoun: 'yo', form: '-o' },
      { pronoun: 'tú', form: '-es' },
      { pronoun: 'él/ella', form: '-e' },
      { pronoun: 'nosotros', form: '-imos' },
      { pronoun: 'vosotros', form: '-ís' },
      { pronoun: 'ellos/ellas', form: '-en' },
    ],
    examples: ['Yo vivo en Madrid.', 'Ella escribe una carta.'],
    commonMistake: 'Using -emos for nosotros (that\'s -er)',
    correctForm: '-ir has -imos for nosotros; -er has -emos.',
  },
  {
    id: 'es-g13',
    title: 'Conditional tense',
    tense: 'condicional',
    coreIdea: 'Infinitive + -ía, -ías, -ía, -íamos, -íais, -ían',
    conjugation: [
      { pronoun: 'yo', form: '-ía' },
      { pronoun: 'tú', form: '-ías' },
      { pronoun: 'él/ella', form: '-ía' },
      { pronoun: 'nosotros', form: '-íamos' },
      { pronoun: 'vosotros', form: '-íais' },
      { pronoun: 'ellos/ellas', form: '-ían' },
    ],
    examples: ['Me gustaría un café.', 'Viajaría a Japón.'],
    commonMistake: 'Confusing conditional with imperfect',
    correctForm: 'Conditional = would + verb. Imperfect = was/were + -ing.',
  },
  {
    id: 'es-g14',
    title: 'Present perfect (haber + past participle)',
    tense: 'pretérito perfecto',
    coreIdea: 'Haber (present) + past participle. For recent past or ongoing relevance.',
    conjugation: [
      { pronoun: 'yo', form: 'he + pp' },
      { pronoun: 'tú', form: 'has + pp' },
      { pronoun: 'él/ella', form: 'ha + pp' },
      { pronoun: 'nosotros', form: 'hemos + pp' },
      { pronoun: 'vosotros', form: 'habéis + pp' },
      { pronoun: 'ellos/ellas', form: 'han + pp' },
    ],
    examples: ['He comido.', 'Ella ha llegado hoy.'],
    commonMistake: 'Using present perfect for a specific completed time (use preterite)',
    correctForm: 'Present perfect = have done (recent/undefined). Preterite = did (specific time).',
  },
  {
    id: 'es-g15',
    title: 'Comparatives and superlatives',
    tense: undefined,
    coreIdea: 'Más...que (more than), menos...que (less than), tan...como (as...as). El/la/los/las más (superlative).',
    examples: ['Es más alto que yo.', 'Es la más bonita.', 'Es tan inteligente como su hermana.'],
    commonMistake: 'Using "más bueno" instead of "mejor"',
    correctForm: 'Bueno → mejor, malo → peor, grande → mayor (for age/size).',
  },
  {
    id: 'es-g16',
    title: 'Indirect object pronouns',
    tense: undefined,
    coreIdea: 'me, te, le, nos, os, les – before verb or attached to infinitive. Le/les become se before lo/la/los/las.',
    examples: ['Le doy el libro.', 'Les hablo.', 'Se lo doy (not le lo).'],
    commonMistake: 'Using "le" for "les" when both appear – use "se" for both',
    correctForm: 'Le/les + lo/la/los/las → se lo, se la, se los, se las.',
  },
  {
    id: 'es-g17',
    title: 'Acabar de + infinitive',
    tense: undefined,
    coreIdea: 'Acabar de + infinitive = to have just done something.',
    examples: ['Acabo de comer.', 'Ella acaba de llegar.'],
    commonMistake: 'Using "acabo comer" without "de"',
    correctForm: '"De" is essential: acabar de + infinitive = just did.',
  },
  {
    id: 'es-g18',
    title: 'Relative pronouns que, quien, donde',
    tense: undefined,
    coreIdea: 'Que = who/which/that. Quien/quienes = who/whom (after preposition). Donde = where.',
    examples: ['El libro que leo es interesante.', 'La mujer con quien hablé.', 'La ciudad donde vivo.'],
    commonMistake: 'Using "que" after a preposition for people – use "quien"',
    correctForm: 'Con quien, para quien, etc. Que for things or as subject/object.',
  },
  {
    id: 'es-g19',
    title: 'Desde, durante, para',
    tense: undefined,
    coreIdea: 'Desde = since/from. Durante = during/for. Para = for (purpose).',
    examples: ['Vivo aquí desde hace cinco años.', 'Trabajé durante dos horas.', 'Estudio para el examen.'],
    commonMistake: 'Using "desde" with preterite for a finished period',
    correctForm: 'Desde hace + present = for (ongoing). Durante + preterite = for (completed).',
  },
  {
    id: 'es-g20',
    title: 'Ir a + infinitive (near future)',
    tense: undefined,
    coreIdea: 'Ir (present) + a + infinitive = to be going to do something.',
    examples: ['Voy a estudiar.', 'Va a llover.'],
    commonMistake: 'Confusing with simple future – ir a = going to, future = will',
    correctForm: 'Voy a + infinitive = I am going to. Future = will (more formal/distant).',
  },
];

export function getGrammarConcepts(lang: LanguageId): MflGrammarConcept[] {
  return lang === 'french' ? FRENCH_GRAMMAR : SPANISH_GRAMMAR;
}

export function getGrammarConceptById(lang: LanguageId, id: string): MflGrammarConcept | undefined {
  return getGrammarConcepts(lang).find((c) => c.id === id);
}
